<?xml version="1.0" encoding="utf-8"?><Database Name="ClubO7_QC" Class="CommonDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=192.168.1.80\sql2014;Initial Catalog=ClubO7_QC;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ECubeCMSConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.AAAAConfigSettings" Member="AAAAConfigSettings">
    <Type Name="AAAAConfigSetting">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="KeyName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="KeyValue" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="KeyDescription" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Module" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="UpdatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="DeletedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DeletedBy" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.RolePermissions" Member="RolePermissions">
    <Type Name="RolePermission">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RoleId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="PageId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="View_Right" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Add_Right" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Edit_Right" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Delete_Right" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Export_Right" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="UpdatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="DeletedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DeletedBy" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.AAAConfigSettings" Member="AAAConfigSettings">
    <Type Name="AAAConfigSetting">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="KeyName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="KeyValue" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="KeyDescription" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.GetPagePermission" Method="GetPagePermission">
    <Parameter Name="PageId" Parameter="pageId" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="UserId" Parameter="userId" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="RoleId" Parameter="roleId" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="GetPagePermissionResult">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="PageId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="RoleId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="ModuleName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PageName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DispalyName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="View_Right" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Add_Right" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Edit_Right" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Delete_Right" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Export_Right" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetEmailConfigurationByProfileName" Method="GetEmailConfigurationByProfileName">
    <Parameter Name="ProfileName" Parameter="profileName" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="GetEmailConfigurationByProfileNameResult">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="ProfileName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SMPTServer" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Port" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EnableSSL" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DisplayName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ReplierEmail" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="IsExchange" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetPropertyInfo" Method="GetPropertyInfo">
    <ElementType Name="GetPropertyInfoResult">
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="City" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="State" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Fax" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EmailId" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Signature" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="EmailClubName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="SMSClubName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ServiceTaxRegNo" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="GSTIN" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="TinNo" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="PANCardNo" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PinCode" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="WebSite" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="CIN" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="SecretarySign" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>