#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcubeWebPortalCMS.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="GCA_QC")]
	public partial class EventTicketDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public EventTicketDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ECubeCMSConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public EventTicketDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EventTicketDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EventTicketDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EventTicketDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MS_GetBookedEventBooking")]
		public ISingleResult<MS_GetBookedEventBookingResult> MS_GetBookedEventBooking([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MemberId", DbType="BigInt")] System.Nullable<long> memberId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EventBookingId", DbType="VarChar(50)")] string eventBookingId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MemberCode", DbType="VarChar(50)")] string memberCode)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), memberId, eventBookingId, memberCode);
			return ((ISingleResult<MS_GetBookedEventBookingResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MS_GetEventBookingDetail")]
		public ISingleResult<MS_GetEventBookingDetailResult> MS_GetEventBookingDetail([global::System.Data.Linq.Mapping.ParameterAttribute(Name="EventBookingID", DbType="Int")] System.Nullable<int> eventBookingID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), eventBookingID);
			return ((ISingleResult<MS_GetEventBookingDetailResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetMemberCodeDropdown")]
		public ISingleResult<GetMemberCodeDropdownResult> GetMemberCodeDropdown([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MemberCode", DbType="VarChar(250)")] string memberCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AllowInActive", DbType="Bit")] System.Nullable<bool> allowInActive, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsForGuest", DbType="Bit")] System.Nullable<bool> isForGuest, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AllowGuest", DbType="Bit")] System.Nullable<bool> allowGuest, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AllowDeleted", DbType="Bit")] System.Nullable<bool> allowDeleted, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AllowMasterCorporate", DbType="Bit")] System.Nullable<bool> allowMasterCorporate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AllowParty", DbType="Bit")] System.Nullable<bool> allowParty)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), memberCode, allowInActive, isForGuest, allowGuest, allowDeleted, allowMasterCorporate, allowParty);
			return ((ISingleResult<GetMemberCodeDropdownResult>)(result.ReturnValue));
		}
	}
	
	public partial class MS_GetBookedEventBookingResult
	{
		
		private string _EventTitle;
		
		private System.Nullable<int> _MemberID;
		
		private int _EventBookingId;
		
		private string _EventDate;
		
		private string _EventStartTime;
		
		private string _MemberCode;
		
		public MS_GetBookedEventBookingResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EventTitle", DbType="VarChar(2000)")]
		public string EventTitle
		{
			get
			{
				return this._EventTitle;
			}
			set
			{
				if ((this._EventTitle != value))
				{
					this._EventTitle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MemberID", DbType="Int")]
		public System.Nullable<int> MemberID
		{
			get
			{
				return this._MemberID;
			}
			set
			{
				if ((this._MemberID != value))
				{
					this._MemberID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EventBookingId", DbType="Int NOT NULL")]
		public int EventBookingId
		{
			get
			{
				return this._EventBookingId;
			}
			set
			{
				if ((this._EventBookingId != value))
				{
					this._EventBookingId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EventDate", DbType="NVarChar(25)")]
		public string EventDate
		{
			get
			{
				return this._EventDate;
			}
			set
			{
				if ((this._EventDate != value))
				{
					this._EventDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EventStartTime", DbType="VarChar(500)")]
		public string EventStartTime
		{
			get
			{
				return this._EventStartTime;
			}
			set
			{
				if ((this._EventStartTime != value))
				{
					this._EventStartTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MemberCode", DbType="VarChar(100)")]
		public string MemberCode
		{
			get
			{
				return this._MemberCode;
			}
			set
			{
				if ((this._MemberCode != value))
				{
					this._MemberCode = value;
				}
			}
		}
	}
	
	public partial class MS_GetEventBookingDetailResult
	{
		
		private int _Id;
		
		private System.Nullable<int> _EventScheduleId;
		
		private System.Nullable<int> _MemberID;
		
		private int _CRMPaymentId;
		
		private System.Nullable<System.DateTime> _BookDate;
		
		private System.Nullable<decimal> _BaseAmount;
		
		private System.Nullable<decimal> _TaxAmount;
		
		private System.Nullable<decimal> _TotalAmount;
		
		private int _Id1;
		
		private System.Nullable<int> _EventBookingId;
		
		private int _SubMemberID;
		
		private int _Guest;
		
		private System.Nullable<int> _TicketsNO;
		
		private System.Nullable<decimal> _UserBaseAmount;
		
		private System.Nullable<decimal> _UserTaxAmount;
		
		private System.Nullable<decimal> _UserTotalAmount;
		
		private System.Nullable<int> _AccountHeadId;
		
		private System.Nullable<int> _TaxMasterId;
		
		private string _EventDate;
		
		private string _UserName;
		
		private string _UserImage;
		
		private string _UserPhoto1;
		
		private string _EventTitle;
		
		private string _EventPlace;
		
		private string _EventDuration;
		
		private string _EventStartTime;
		
		private string _EventEndTime;
		
		private string _MemberName;
		
		private string _ClubName;
		
		private string _ClubAddress;
		
		private string _Signature;
		
		private string _PaymentType;
		
		private System.Nullable<bool> _IsQRCode;
		
		private string _EventTicketCategoryName;
		
		private int _EventTicketNo;
		
		public MS_GetEventBookingDetailResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EventScheduleId", DbType="Int")]
		public System.Nullable<int> EventScheduleId
		{
			get
			{
				return this._EventScheduleId;
			}
			set
			{
				if ((this._EventScheduleId != value))
				{
					this._EventScheduleId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MemberID", DbType="Int")]
		public System.Nullable<int> MemberID
		{
			get
			{
				return this._MemberID;
			}
			set
			{
				if ((this._MemberID != value))
				{
					this._MemberID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CRMPaymentId", DbType="Int NOT NULL")]
		public int CRMPaymentId
		{
			get
			{
				return this._CRMPaymentId;
			}
			set
			{
				if ((this._CRMPaymentId != value))
				{
					this._CRMPaymentId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> BookDate
		{
			get
			{
				return this._BookDate;
			}
			set
			{
				if ((this._BookDate != value))
				{
					this._BookDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaseAmount", DbType="Decimal(18,4)")]
		public System.Nullable<decimal> BaseAmount
		{
			get
			{
				return this._BaseAmount;
			}
			set
			{
				if ((this._BaseAmount != value))
				{
					this._BaseAmount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxAmount", DbType="Decimal(18,4)")]
		public System.Nullable<decimal> TaxAmount
		{
			get
			{
				return this._TaxAmount;
			}
			set
			{
				if ((this._TaxAmount != value))
				{
					this._TaxAmount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalAmount", DbType="Decimal(18,4)")]
		public System.Nullable<decimal> TotalAmount
		{
			get
			{
				return this._TotalAmount;
			}
			set
			{
				if ((this._TotalAmount != value))
				{
					this._TotalAmount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id1", DbType="Int NOT NULL")]
		public int Id1
		{
			get
			{
				return this._Id1;
			}
			set
			{
				if ((this._Id1 != value))
				{
					this._Id1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EventBookingId", DbType="Int")]
		public System.Nullable<int> EventBookingId
		{
			get
			{
				return this._EventBookingId;
			}
			set
			{
				if ((this._EventBookingId != value))
				{
					this._EventBookingId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubMemberID", DbType="Int NOT NULL")]
		public int SubMemberID
		{
			get
			{
				return this._SubMemberID;
			}
			set
			{
				if ((this._SubMemberID != value))
				{
					this._SubMemberID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Guest", DbType="Int NOT NULL")]
		public int Guest
		{
			get
			{
				return this._Guest;
			}
			set
			{
				if ((this._Guest != value))
				{
					this._Guest = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TicketsNO", DbType="Int")]
		public System.Nullable<int> TicketsNO
		{
			get
			{
				return this._TicketsNO;
			}
			set
			{
				if ((this._TicketsNO != value))
				{
					this._TicketsNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserBaseAmount", DbType="Decimal(18,4)")]
		public System.Nullable<decimal> UserBaseAmount
		{
			get
			{
				return this._UserBaseAmount;
			}
			set
			{
				if ((this._UserBaseAmount != value))
				{
					this._UserBaseAmount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserTaxAmount", DbType="Decimal(18,4)")]
		public System.Nullable<decimal> UserTaxAmount
		{
			get
			{
				return this._UserTaxAmount;
			}
			set
			{
				if ((this._UserTaxAmount != value))
				{
					this._UserTaxAmount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserTotalAmount", DbType="Decimal(18,4)")]
		public System.Nullable<decimal> UserTotalAmount
		{
			get
			{
				return this._UserTotalAmount;
			}
			set
			{
				if ((this._UserTotalAmount != value))
				{
					this._UserTotalAmount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountHeadId", DbType="Int")]
		public System.Nullable<int> AccountHeadId
		{
			get
			{
				return this._AccountHeadId;
			}
			set
			{
				if ((this._AccountHeadId != value))
				{
					this._AccountHeadId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxMasterId", DbType="Int")]
		public System.Nullable<int> TaxMasterId
		{
			get
			{
				return this._TaxMasterId;
			}
			set
			{
				if ((this._TaxMasterId != value))
				{
					this._TaxMasterId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EventDate", DbType="NVarChar(MAX)")]
		public string EventDate
		{
			get
			{
				return this._EventDate;
			}
			set
			{
				if ((this._EventDate != value))
				{
					this._EventDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(255)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserImage", DbType="NVarChar(1600) NOT NULL", CanBeNull=false)]
		public string UserImage
		{
			get
			{
				return this._UserImage;
			}
			set
			{
				if ((this._UserImage != value))
				{
					this._UserImage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserPhoto1", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string UserPhoto1
		{
			get
			{
				return this._UserPhoto1;
			}
			set
			{
				if ((this._UserPhoto1 != value))
				{
					this._UserPhoto1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EventTitle", DbType="VarChar(2000)")]
		public string EventTitle
		{
			get
			{
				return this._EventTitle;
			}
			set
			{
				if ((this._EventTitle != value))
				{
					this._EventTitle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EventPlace", DbType="VarChar(MAX)")]
		public string EventPlace
		{
			get
			{
				return this._EventPlace;
			}
			set
			{
				if ((this._EventPlace != value))
				{
					this._EventPlace = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EventDuration", DbType="VarChar(200)")]
		public string EventDuration
		{
			get
			{
				return this._EventDuration;
			}
			set
			{
				if ((this._EventDuration != value))
				{
					this._EventDuration = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EventStartTime", DbType="VarChar(500)")]
		public string EventStartTime
		{
			get
			{
				return this._EventStartTime;
			}
			set
			{
				if ((this._EventStartTime != value))
				{
					this._EventStartTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EventEndTime", DbType="VarChar(500)")]
		public string EventEndTime
		{
			get
			{
				return this._EventEndTime;
			}
			set
			{
				if ((this._EventEndTime != value))
				{
					this._EventEndTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MemberName", DbType="VarChar(101)")]
		public string MemberName
		{
			get
			{
				return this._MemberName;
			}
			set
			{
				if ((this._MemberName != value))
				{
					this._MemberName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClubName", DbType="NVarChar(MAX)")]
		public string ClubName
		{
			get
			{
				return this._ClubName;
			}
			set
			{
				if ((this._ClubName != value))
				{
					this._ClubName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClubAddress", DbType="NVarChar(MAX)")]
		public string ClubAddress
		{
			get
			{
				return this._ClubAddress;
			}
			set
			{
				if ((this._ClubAddress != value))
				{
					this._ClubAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Signature", DbType="NVarChar(100)")]
		public string Signature
		{
			get
			{
				return this._Signature;
			}
			set
			{
				if ((this._Signature != value))
				{
					this._Signature = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentType", DbType="VarChar(100)")]
		public string PaymentType
		{
			get
			{
				return this._PaymentType;
			}
			set
			{
				if ((this._PaymentType != value))
				{
					this._PaymentType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsQRCode", DbType="Bit")]
		public System.Nullable<bool> IsQRCode
		{
			get
			{
				return this._IsQRCode;
			}
			set
			{
				if ((this._IsQRCode != value))
				{
					this._IsQRCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EventTicketCategoryName", DbType="VarChar(500)")]
		public string EventTicketCategoryName
		{
			get
			{
				return this._EventTicketCategoryName;
			}
			set
			{
				if ((this._EventTicketCategoryName != value))
				{
					this._EventTicketCategoryName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EventTicketNo", DbType="Int NOT NULL")]
		public int EventTicketNo
		{
			get
			{
				return this._EventTicketNo;
			}
			set
			{
				if ((this._EventTicketNo != value))
				{
					this._EventTicketNo = value;
				}
			}
		}
	}
	
	//public partial class GetMemberCodeDropdownResult
	//{
		
	//	private decimal _Id2;
		
	//	private string _Name2;
		
	//	public GetMemberCodeDropdownResult()
	//	{
	//	}
		
	//	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Decimal(18,0) NOT NULL")]
	//	public decimal Id2
	//	{
	//		get
	//		{
	//			return this._Id2;
	//		}
	//		set
	//		{
	//			if ((this._Id2 != value))
	//			{
	//				this._Id2 = value;
	//			}
	//		}
	//	}
		
	//	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(255)")]
	//	public string Name2
	//	{
	//		get
	//		{
	//			return this._Name2;
	//		}
	//		set
	//		{
	//			if ((this._Name2 != value))
	//			{
	//				this._Name2 = value;
	//			}
	//		}
	//	}
	//}
}
#pragma warning restore 1591
