<?xml version="1.0" encoding="utf-8"?><Database Name="karnavati_qc" Class="InformationDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=192.168.1.80\sql2012;Initial Catalog=karnavati_qc;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ECubeCMSConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Information" Member="Informations">
    <Type Name="Information">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ImagePath" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UpdatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DeletedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DeletedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SequenceNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.DeleteInformation" Method="DeleteInformation">
    <Parameter Name="IdList" Parameter="idList" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="DeletedBy" Parameter="deletedBy" Type="System.Int32" DbType="Int" />
    <Parameter Name="PageId" Parameter="pageId" Type="System.Int32" DbType="Int" />
    <ElementType Name="DeleteInformationResult">
      <Column Name="TotalReference" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SearchInformation" Method="SearchInformation">
    <Parameter Name="Rows" Parameter="rows" Type="System.Int32" DbType="Int" />
    <Parameter Name="Page" Parameter="page" Type="System.Int32" DbType="Int" />
    <Parameter Name="Search" Parameter="search" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="Sort" Parameter="sort" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="SearchInformationResult">
      <Column Name="RowNum" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Total" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="InformationName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="InformationDescription" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="SequenceNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.InsertOrUpdateInformation" Method="InsertOrUpdateInformation">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Description" Parameter="description" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="Image" Parameter="image" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="SequenceNo" Parameter="sequenceNo" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <Parameter Name="PageId" Parameter="pageId" Type="System.Int32" DbType="Int" />
    <ElementType Name="InsertOrUpdateInformationResult">
      <Column Name="InsertedId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>