#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcubeWebPortalCMS.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ClubO7_Dev")]
	public partial class MenuMobileDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertMenuMobile(MenuMobile instance);
    partial void UpdateMenuMobile(MenuMobile instance);
    partial void DeleteMenuMobile(MenuMobile instance);
    #endregion
		
		public MenuMobileDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ECubeCMSConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MenuMobileDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MenuMobileDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MenuMobileDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MenuMobileDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<MenuMobile> MenuMobiles
		{
			get
			{
				return this.GetTable<MenuMobile>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertOrUpdateMenu")]
		public ISingleResult<InsertOrUpdateMenuResult> InsertOrUpdateMenu([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MenuId", DbType="Int")] System.Nullable<int> menuId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ParentMenuId", DbType="Int")] System.Nullable<int> parentMenuId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SeqNo", DbType="Int")] System.Nullable<int> seqNo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MenuKey", DbType="NVarChar(100)")] string menuKey, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MenuDisplayName", DbType="NVarChar(100)")] string menuDisplayName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MenuIcon", DbType="NVarChar(100)")] string menuIcon, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserId", DbType="Int")] System.Nullable<int> userId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageId", DbType="Int")] System.Nullable<int> pageId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), menuId, parentMenuId, seqNo, menuKey, menuDisplayName, menuIcon, userId, pageId);
			return ((ISingleResult<InsertOrUpdateMenuResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertOrUpdateSubMenu")]
		public ISingleResult<InsertOrUpdateSubMenuResult> InsertOrUpdateSubMenu([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MenuId", DbType="Int")] System.Nullable<int> menuId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ParentMenuId", DbType="Int")] System.Nullable<int> parentMenuId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SeqNo", DbType="Int")] System.Nullable<int> seqNo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MenuKey", DbType="NVarChar(100)")] string menuKey, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MenuDisplayName", DbType="NVarChar(100)")] string menuDisplayName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MenuIcon", DbType="NVarChar(100)")] string menuIcon, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserId", DbType="Int")] System.Nullable<int> userId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageId", DbType="Int")] System.Nullable<int> pageId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), menuId, parentMenuId, seqNo, menuKey, menuDisplayName, menuIcon, userId, pageId);
			return ((ISingleResult<InsertOrUpdateSubMenuResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DeleteMobileMenu")]
		public ISingleResult<DeleteMobileMenuResult> DeleteMobileMenu([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdList", DbType="VarChar(50)")] string idList, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DeletedBy", DbType="Int")] System.Nullable<int> deletedBy, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageId", DbType="Int")] System.Nullable<int> pageId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idList, deletedBy, pageId);
			return ((ISingleResult<DeleteMobileMenuResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SearchMenuMobile")]
		public ISingleResult<SearchMenuMobileResult> SearchMenuMobile([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Rows", DbType="Int")] System.Nullable<int> rows, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Page", DbType="Int")] System.Nullable<int> page, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Search", DbType="VarChar(500)")] string search, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Sort", DbType="VarChar(50)")] string sort)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), rows, page, search, sort);
			return ((ISingleResult<SearchMenuMobileResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MenuMobile")]
	public partial class MenuMobile : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MenuId;
		
		private System.Nullable<int> _ParentMenuId;
		
		private System.Nullable<int> _SeqNo;
		
		private string _MenuKey;
		
		private string _MenuDisplayName;
		
		private string _MenuIcon;
		
		private System.Nullable<bool> _IsSportsService;
		
		private System.Nullable<long> _ServicesId;
		
		private System.Nullable<long> _CreatedBy;
		
		private System.Nullable<System.DateTime> _CreatedOn;
		
		private System.Nullable<long> _UpdatedBy;
		
		private System.Nullable<System.DateTime> _UpdatedOn;
		
		private System.Nullable<long> _DeletedBy;
		
		private System.Nullable<System.DateTime> _DeletedOn;
		
		private System.Nullable<bool> _IsDeleted;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMenuIdChanging(int value);
    partial void OnMenuIdChanged();
    partial void OnParentMenuIdChanging(System.Nullable<int> value);
    partial void OnParentMenuIdChanged();
    partial void OnSeqNoChanging(System.Nullable<int> value);
    partial void OnSeqNoChanged();
    partial void OnMenuKeyChanging(string value);
    partial void OnMenuKeyChanged();
    partial void OnMenuDisplayNameChanging(string value);
    partial void OnMenuDisplayNameChanged();
    partial void OnMenuIconChanging(string value);
    partial void OnMenuIconChanged();
    partial void OnIsSportsServiceChanging(System.Nullable<bool> value);
    partial void OnIsSportsServiceChanged();
    partial void OnServicesIdChanging(System.Nullable<long> value);
    partial void OnServicesIdChanged();
    partial void OnCreatedByChanging(System.Nullable<long> value);
    partial void OnCreatedByChanged();
    partial void OnCreatedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedOnChanged();
    partial void OnUpdatedByChanging(System.Nullable<long> value);
    partial void OnUpdatedByChanged();
    partial void OnUpdatedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdatedOnChanged();
    partial void OnDeletedByChanging(System.Nullable<long> value);
    partial void OnDeletedByChanged();
    partial void OnDeletedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnDeletedOnChanged();
    partial void OnIsDeletedChanging(System.Nullable<bool> value);
    partial void OnIsDeletedChanged();
    #endregion
		
		public MenuMobile()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenuId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MenuId
		{
			get
			{
				return this._MenuId;
			}
			set
			{
				if ((this._MenuId != value))
				{
					this.OnMenuIdChanging(value);
					this.SendPropertyChanging();
					this._MenuId = value;
					this.SendPropertyChanged("MenuId");
					this.OnMenuIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentMenuId", DbType="Int")]
		public System.Nullable<int> ParentMenuId
		{
			get
			{
				return this._ParentMenuId;
			}
			set
			{
				if ((this._ParentMenuId != value))
				{
					this.OnParentMenuIdChanging(value);
					this.SendPropertyChanging();
					this._ParentMenuId = value;
					this.SendPropertyChanged("ParentMenuId");
					this.OnParentMenuIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SeqNo", DbType="Int")]
		public System.Nullable<int> SeqNo
		{
			get
			{
				return this._SeqNo;
			}
			set
			{
				if ((this._SeqNo != value))
				{
					this.OnSeqNoChanging(value);
					this.SendPropertyChanging();
					this._SeqNo = value;
					this.SendPropertyChanged("SeqNo");
					this.OnSeqNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenuKey", DbType="NVarChar(100)")]
		public string MenuKey
		{
			get
			{
				return this._MenuKey;
			}
			set
			{
				if ((this._MenuKey != value))
				{
					this.OnMenuKeyChanging(value);
					this.SendPropertyChanging();
					this._MenuKey = value;
					this.SendPropertyChanged("MenuKey");
					this.OnMenuKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenuDisplayName", DbType="NVarChar(100)")]
		public string MenuDisplayName
		{
			get
			{
				return this._MenuDisplayName;
			}
			set
			{
				if ((this._MenuDisplayName != value))
				{
					this.OnMenuDisplayNameChanging(value);
					this.SendPropertyChanging();
					this._MenuDisplayName = value;
					this.SendPropertyChanged("MenuDisplayName");
					this.OnMenuDisplayNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenuIcon", DbType="NVarChar(100)")]
		public string MenuIcon
		{
			get
			{
				return this._MenuIcon;
			}
			set
			{
				if ((this._MenuIcon != value))
				{
					this.OnMenuIconChanging(value);
					this.SendPropertyChanging();
					this._MenuIcon = value;
					this.SendPropertyChanged("MenuIcon");
					this.OnMenuIconChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsSportsService", DbType="Bit")]
		public System.Nullable<bool> IsSportsService
		{
			get
			{
				return this._IsSportsService;
			}
			set
			{
				if ((this._IsSportsService != value))
				{
					this.OnIsSportsServiceChanging(value);
					this.SendPropertyChanging();
					this._IsSportsService = value;
					this.SendPropertyChanged("IsSportsService");
					this.OnIsSportsServiceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ServicesId", DbType="BigInt")]
		public System.Nullable<long> ServicesId
		{
			get
			{
				return this._ServicesId;
			}
			set
			{
				if ((this._ServicesId != value))
				{
					this.OnServicesIdChanging(value);
					this.SendPropertyChanging();
					this._ServicesId = value;
					this.SendPropertyChanged("ServicesId");
					this.OnServicesIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="BigInt")]
		public System.Nullable<long> CreatedBy
		{
			get
			{
				return this._CreatedBy;
			}
			set
			{
				if ((this._CreatedBy != value))
				{
					this.OnCreatedByChanging(value);
					this.SendPropertyChanging();
					this._CreatedBy = value;
					this.SendPropertyChanged("CreatedBy");
					this.OnCreatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this._CreatedOn;
			}
			set
			{
				if ((this._CreatedOn != value))
				{
					this.OnCreatedOnChanging(value);
					this.SendPropertyChanging();
					this._CreatedOn = value;
					this.SendPropertyChanged("CreatedOn");
					this.OnCreatedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedBy", DbType="BigInt")]
		public System.Nullable<long> UpdatedBy
		{
			get
			{
				return this._UpdatedBy;
			}
			set
			{
				if ((this._UpdatedBy != value))
				{
					this.OnUpdatedByChanging(value);
					this.SendPropertyChanging();
					this._UpdatedBy = value;
					this.SendPropertyChanged("UpdatedBy");
					this.OnUpdatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdatedOn
		{
			get
			{
				return this._UpdatedOn;
			}
			set
			{
				if ((this._UpdatedOn != value))
				{
					this.OnUpdatedOnChanging(value);
					this.SendPropertyChanging();
					this._UpdatedOn = value;
					this.SendPropertyChanged("UpdatedOn");
					this.OnUpdatedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeletedBy", DbType="BigInt")]
		public System.Nullable<long> DeletedBy
		{
			get
			{
				return this._DeletedBy;
			}
			set
			{
				if ((this._DeletedBy != value))
				{
					this.OnDeletedByChanging(value);
					this.SendPropertyChanging();
					this._DeletedBy = value;
					this.SendPropertyChanged("DeletedBy");
					this.OnDeletedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeletedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> DeletedOn
		{
			get
			{
				return this._DeletedOn;
			}
			set
			{
				if ((this._DeletedOn != value))
				{
					this.OnDeletedOnChanging(value);
					this.SendPropertyChanging();
					this._DeletedOn = value;
					this.SendPropertyChanged("DeletedOn");
					this.OnDeletedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Bit")]
		public System.Nullable<bool> IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this.OnIsDeletedChanging(value);
					this.SendPropertyChanging();
					this._IsDeleted = value;
					this.SendPropertyChanged("IsDeleted");
					this.OnIsDeletedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class InsertOrUpdateMenuResult
	{
		
		private int _InsertedId;
		
		public InsertOrUpdateMenuResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InsertedId", DbType="Int NOT NULL")]
		public int InsertedId
		{
			get
			{
				return this._InsertedId;
			}
			set
			{
				if ((this._InsertedId != value))
				{
					this._InsertedId = value;
				}
			}
		}
	}
	
	public partial class InsertOrUpdateSubMenuResult
	{
		
		private int _InsertedSubMenuId;
		
		public InsertOrUpdateSubMenuResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InsertedSubMenuId", DbType="Int NOT NULL")]
		public int InsertedSubMenuId
		{
			get
			{
				return this._InsertedSubMenuId;
			}
			set
			{
				if ((this._InsertedSubMenuId != value))
				{
					this._InsertedSubMenuId = value;
				}
			}
		}
	}
	
	public partial class DeleteMobileMenuResult
	{
		
		private int _TotalReference;
		
		private string _Name;
		
		public DeleteMobileMenuResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalReference", DbType="Int NOT NULL")]
		public int TotalReference
		{
			get
			{
				return this._TotalReference;
			}
			set
			{
				if ((this._TotalReference != value))
				{
					this._TotalReference = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(250)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
	}
	
	public partial class SearchMenuMobileResult
	{
		
		private System.Nullable<long> _RowNum;
		
		private System.Nullable<int> _Total;
		
		private int _MenuId;
		
		private string _MenuKey;
		
		private string _MenuDisplayName;
		
		private System.Nullable<int> _SeqNo;
		
		private string _SubMenu;
		
		public SearchMenuMobileResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RowNum", DbType="BigInt")]
		public System.Nullable<long> RowNum
		{
			get
			{
				return this._RowNum;
			}
			set
			{
				if ((this._RowNum != value))
				{
					this._RowNum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", DbType="Int")]
		public System.Nullable<int> Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this._Total = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenuId", DbType="Int NOT NULL")]
		public int MenuId
		{
			get
			{
				return this._MenuId;
			}
			set
			{
				if ((this._MenuId != value))
				{
					this._MenuId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenuKey", DbType="NVarChar(100)")]
		public string MenuKey
		{
			get
			{
				return this._MenuKey;
			}
			set
			{
				if ((this._MenuKey != value))
				{
					this._MenuKey = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenuDisplayName", DbType="NVarChar(100)")]
		public string MenuDisplayName
		{
			get
			{
				return this._MenuDisplayName;
			}
			set
			{
				if ((this._MenuDisplayName != value))
				{
					this._MenuDisplayName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SeqNo", DbType="Int")]
		public System.Nullable<int> SeqNo
		{
			get
			{
				return this._SeqNo;
			}
			set
			{
				if ((this._SeqNo != value))
				{
					this._SeqNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubMenu", DbType="NVarChar(MAX)")]
		public string SubMenu
		{
			get
			{
				return this._SubMenu;
			}
			set
			{
				if ((this._SubMenu != value))
				{
					this._SubMenu = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
