#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcubeWebPortalCMS.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ClubO7_Dev")]
	public partial class MovieDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertMovieTheatreShow(MovieTheatreShow instance);
    partial void UpdateMovieTheatreShow(MovieTheatreShow instance);
    partial void DeleteMovieTheatreShow(MovieTheatreShow instance);
    partial void InsertMovie(Movie instance);
    partial void UpdateMovie(Movie instance);
    partial void DeleteMovie(Movie instance);
    #endregion
		
		public MovieDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ECubeCMSConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MovieDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MovieDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MovieDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MovieDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<MovieTheatreShow> MovieTheatreShows
		{
			get
			{
				return this.GetTable<MovieTheatreShow>();
			}
		}
		
		public System.Data.Linq.Table<Movie> Movies
		{
			get
			{
				return this.GetTable<Movie>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CountMovie")]
		public ISingleResult<CountMovieResult> CountMovie()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<CountMovieResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CountMovieTheatreShow")]
		public ISingleResult<CountMovieTheatreShowResult> CountMovieTheatreShow()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<CountMovieTheatreShowResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DeleteMovie")]
		public ISingleResult<DeleteMovieResult> DeleteMovie([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdList", DbType="NVarChar(MAX)")] string idList, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DeletedBy", DbType="BigInt")] System.Nullable<long> deletedBy, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageId", DbType="BigInt")] System.Nullable<long> pageId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idList, deletedBy, pageId);
			return ((ISingleResult<DeleteMovieResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DeleteMovieTheatreShow")]
		public ISingleResult<DeleteMovieTheatreShowResult> DeleteMovieTheatreShow([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdList", DbType="NVarChar(MAX)")] string idList, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DeletedBy", DbType="BigInt")] System.Nullable<long> deletedBy, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageId", DbType="BigInt")] System.Nullable<long> pageId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idList, deletedBy, pageId);
			return ((ISingleResult<DeleteMovieTheatreShowResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetMovieAll")]
		public ISingleResult<GetMovieAllResult> GetMovieAll()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<GetMovieAllResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetMovieTheatreShowById")]
		public ISingleResult<GetMovieTheatreShowByIdResult> GetMovieTheatreShowById([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="BigInt")] System.Nullable<long> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((ISingleResult<GetMovieTheatreShowByIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SearchMovieTheatreShow")]
		public ISingleResult<SearchMovieTheatreShowResult> SearchMovieTheatreShow([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Rows", DbType="Int")] System.Nullable<int> rows, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Page", DbType="Int")] System.Nullable<int> page, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Search", DbType="NVarChar(500)")] string search, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Sort", DbType="NVarChar(50)")] string sort)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), rows, page, search, sort);
			return ((ISingleResult<SearchMovieTheatreShowResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertOrUpdateMovieTheatreShow")]
		public ISingleResult<InsertOrUpdateMovieTheatreShowResult> InsertOrUpdateMovieTheatreShow([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="BigInt")] System.Nullable<long> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MovieTheatreShowName", DbType="NVarChar(50)")] string movieTheatreShowName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ShowKeyDate", DbType="DateTime")] System.Nullable<System.DateTime> showKeyDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MovieTheatreId", DbType="BigInt")] System.Nullable<long> movieTheatreId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MovieShowId", DbType="BigInt")] System.Nullable<long> movieShowId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MovieId", DbType="BigInt")] System.Nullable<long> movieId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MemberAmount", DbType="Decimal(18,0)")] System.Nullable<decimal> memberAmount, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GuestAmount", DbType="Decimal(18,0)")] System.Nullable<decimal> guestAmount, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserId", DbType="BigInt")] System.Nullable<long> userId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageId", DbType="BigInt")] System.Nullable<long> pageId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, movieTheatreShowName, showKeyDate, movieTheatreId, movieShowId, movieId, memberAmount, guestAmount, userId, pageId);
			return ((ISingleResult<InsertOrUpdateMovieTheatreShowResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetMovieTheatreShowByMovieId")]
		public ISingleResult<GetMovieTheatreShowByMovieIdResult> GetMovieTheatreShowByMovieId([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MovieId", DbType="BigInt")] System.Nullable<long> movieId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), movieId);
			return ((ISingleResult<GetMovieTheatreShowByMovieIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SearchMovie")]
		public ISingleResult<SearchMovieResult> SearchMovie([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Rows", DbType="Int")] System.Nullable<int> rows, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Page", DbType="Int")] System.Nullable<int> page, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Search", DbType="NVarChar(500)")] string search, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Sort", DbType="NVarChar(50)")] string sort, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsActive", DbType="Bit")] System.Nullable<bool> isActive)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), rows, page, search, sort, isActive);
			return ((ISingleResult<SearchMovieResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetMovieShowForInActiveMovie")]
		public ISingleResult<GetMovieShowForInActiveMovieResult> GetMovieShowForInActiveMovie([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MovieId", DbType="Int")] System.Nullable<int> movieId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), movieId);
			return ((ISingleResult<GetMovieShowForInActiveMovieResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetMovieById")]
		public ISingleResult<GetMovieByIdResult> GetMovieById([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="BigInt")] System.Nullable<long> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((ISingleResult<GetMovieByIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertOrUpdateMovie")]
		public ISingleResult<InsertOrUpdateMovieResult> InsertOrUpdateMovie([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="BigInt")] System.Nullable<long> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MovieName", DbType="NVarChar(50)")] string movieName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MovieCategory", DbType="NVarChar(20)")] string movieCategory, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MovieRating", DbType="NVarChar(5)")] string movieRating, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MovieLanguage", DbType="NVarChar(100)")] string movieLanguage, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MovieContentType", DbType="NVarChar(50)")] string movieContentType, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MovieType", DbType="NVarChar(50)")] string movieType, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Image", DbType="VarChar(255)")] string image, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsActive", DbType="Bit")] System.Nullable<bool> isActive, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserId", DbType="BigInt")] System.Nullable<long> userId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageId", DbType="BigInt")] System.Nullable<long> pageId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AppDescription", DbType="VarChar(250)")] string appDescription, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EntryAfter", DbType="Int")] System.Nullable<int> entryAfter, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EntryBefore", DbType="Int")] System.Nullable<int> entryBefore, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MobileImage", DbType="VarChar(50)")] string mobileImage)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, movieName, movieCategory, movieRating, movieLanguage, movieContentType, movieType, image, isActive, userId, pageId, appDescription, entryAfter, entryBefore, mobileImage);
			return ((ISingleResult<InsertOrUpdateMovieResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MovieTheatreShow")]
	public partial class MovieTheatreShow : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private string _MovieTheatreShowName;
		
		private System.Nullable<System.DateTime> _ShowKeyDate;
		
		private System.Nullable<long> _MovieTheatreId;
		
		private System.Nullable<long> _MovieShowId;
		
		private long _MovieId;
		
		private System.DateTime _CreatedOn;
		
		private long _CreatedBy;
		
		private System.Nullable<System.DateTime> _UpdatedOn;
		
		private System.Nullable<long> _UpdatedBy;
		
		private System.Nullable<System.DateTime> _DeletedOn;
		
		private System.Nullable<long> _DeletedBy;
		
		private bool _IsDeleted;
		
		private System.Nullable<decimal> _MemberAmount;
		
		private System.Nullable<decimal> _GuestAmount;
		
		private string _UploadedImage;
		
		private EntityRef<Movie> _Movie;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnMovieTheatreShowNameChanging(string value);
    partial void OnMovieTheatreShowNameChanged();
    partial void OnShowKeyDateChanging(System.Nullable<System.DateTime> value);
    partial void OnShowKeyDateChanged();
    partial void OnMovieTheatreIdChanging(System.Nullable<long> value);
    partial void OnMovieTheatreIdChanged();
    partial void OnMovieShowIdChanging(System.Nullable<long> value);
    partial void OnMovieShowIdChanged();
    partial void OnMovieIdChanging(long value);
    partial void OnMovieIdChanged();
    partial void OnCreatedOnChanging(System.DateTime value);
    partial void OnCreatedOnChanged();
    partial void OnCreatedByChanging(long value);
    partial void OnCreatedByChanged();
    partial void OnUpdatedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdatedOnChanged();
    partial void OnUpdatedByChanging(System.Nullable<long> value);
    partial void OnUpdatedByChanged();
    partial void OnDeletedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnDeletedOnChanged();
    partial void OnDeletedByChanging(System.Nullable<long> value);
    partial void OnDeletedByChanged();
    partial void OnIsDeletedChanging(bool value);
    partial void OnIsDeletedChanged();
    partial void OnMemberAmountChanging(System.Nullable<decimal> value);
    partial void OnMemberAmountChanged();
    partial void OnGuestAmountChanging(System.Nullable<decimal> value);
    partial void OnGuestAmountChanged();
    partial void OnUploadedImageChanging(string value);
    partial void OnUploadedImageChanged();
    #endregion
		
		public MovieTheatreShow()
		{
			this._Movie = default(EntityRef<Movie>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MovieTheatreShowName", DbType="NVarChar(50)")]
		public string MovieTheatreShowName
		{
			get
			{
				return this._MovieTheatreShowName;
			}
			set
			{
				if ((this._MovieTheatreShowName != value))
				{
					this.OnMovieTheatreShowNameChanging(value);
					this.SendPropertyChanging();
					this._MovieTheatreShowName = value;
					this.SendPropertyChanged("MovieTheatreShowName");
					this.OnMovieTheatreShowNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShowKeyDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ShowKeyDate
		{
			get
			{
				return this._ShowKeyDate;
			}
			set
			{
				if ((this._ShowKeyDate != value))
				{
					this.OnShowKeyDateChanging(value);
					this.SendPropertyChanging();
					this._ShowKeyDate = value;
					this.SendPropertyChanged("ShowKeyDate");
					this.OnShowKeyDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MovieTheatreId", DbType="BigInt")]
		public System.Nullable<long> MovieTheatreId
		{
			get
			{
				return this._MovieTheatreId;
			}
			set
			{
				if ((this._MovieTheatreId != value))
				{
					this.OnMovieTheatreIdChanging(value);
					this.SendPropertyChanging();
					this._MovieTheatreId = value;
					this.SendPropertyChanged("MovieTheatreId");
					this.OnMovieTheatreIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MovieShowId", DbType="BigInt")]
		public System.Nullable<long> MovieShowId
		{
			get
			{
				return this._MovieShowId;
			}
			set
			{
				if ((this._MovieShowId != value))
				{
					this.OnMovieShowIdChanging(value);
					this.SendPropertyChanging();
					this._MovieShowId = value;
					this.SendPropertyChanged("MovieShowId");
					this.OnMovieShowIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MovieId", DbType="BigInt NOT NULL")]
		public long MovieId
		{
			get
			{
				return this._MovieId;
			}
			set
			{
				if ((this._MovieId != value))
				{
					if (this._Movie.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMovieIdChanging(value);
					this.SendPropertyChanging();
					this._MovieId = value;
					this.SendPropertyChanged("MovieId");
					this.OnMovieIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOn", DbType="DateTime NOT NULL")]
		public System.DateTime CreatedOn
		{
			get
			{
				return this._CreatedOn;
			}
			set
			{
				if ((this._CreatedOn != value))
				{
					this.OnCreatedOnChanging(value);
					this.SendPropertyChanging();
					this._CreatedOn = value;
					this.SendPropertyChanged("CreatedOn");
					this.OnCreatedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="BigInt NOT NULL")]
		public long CreatedBy
		{
			get
			{
				return this._CreatedBy;
			}
			set
			{
				if ((this._CreatedBy != value))
				{
					this.OnCreatedByChanging(value);
					this.SendPropertyChanging();
					this._CreatedBy = value;
					this.SendPropertyChanged("CreatedBy");
					this.OnCreatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdatedOn
		{
			get
			{
				return this._UpdatedOn;
			}
			set
			{
				if ((this._UpdatedOn != value))
				{
					this.OnUpdatedOnChanging(value);
					this.SendPropertyChanging();
					this._UpdatedOn = value;
					this.SendPropertyChanged("UpdatedOn");
					this.OnUpdatedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedBy", DbType="BigInt")]
		public System.Nullable<long> UpdatedBy
		{
			get
			{
				return this._UpdatedBy;
			}
			set
			{
				if ((this._UpdatedBy != value))
				{
					this.OnUpdatedByChanging(value);
					this.SendPropertyChanging();
					this._UpdatedBy = value;
					this.SendPropertyChanged("UpdatedBy");
					this.OnUpdatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeletedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> DeletedOn
		{
			get
			{
				return this._DeletedOn;
			}
			set
			{
				if ((this._DeletedOn != value))
				{
					this.OnDeletedOnChanging(value);
					this.SendPropertyChanging();
					this._DeletedOn = value;
					this.SendPropertyChanged("DeletedOn");
					this.OnDeletedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeletedBy", DbType="BigInt")]
		public System.Nullable<long> DeletedBy
		{
			get
			{
				return this._DeletedBy;
			}
			set
			{
				if ((this._DeletedBy != value))
				{
					this.OnDeletedByChanging(value);
					this.SendPropertyChanging();
					this._DeletedBy = value;
					this.SendPropertyChanged("DeletedBy");
					this.OnDeletedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Bit NOT NULL")]
		public bool IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this.OnIsDeletedChanging(value);
					this.SendPropertyChanging();
					this._IsDeleted = value;
					this.SendPropertyChanged("IsDeleted");
					this.OnIsDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MemberAmount", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> MemberAmount
		{
			get
			{
				return this._MemberAmount;
			}
			set
			{
				if ((this._MemberAmount != value))
				{
					this.OnMemberAmountChanging(value);
					this.SendPropertyChanging();
					this._MemberAmount = value;
					this.SendPropertyChanged("MemberAmount");
					this.OnMemberAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GuestAmount", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> GuestAmount
		{
			get
			{
				return this._GuestAmount;
			}
			set
			{
				if ((this._GuestAmount != value))
				{
					this.OnGuestAmountChanging(value);
					this.SendPropertyChanging();
					this._GuestAmount = value;
					this.SendPropertyChanged("GuestAmount");
					this.OnGuestAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UploadedImage", DbType="VarChar(255)")]
		public string UploadedImage
		{
			get
			{
				return this._UploadedImage;
			}
			set
			{
				if ((this._UploadedImage != value))
				{
					this.OnUploadedImageChanging(value);
					this.SendPropertyChanging();
					this._UploadedImage = value;
					this.SendPropertyChanged("UploadedImage");
					this.OnUploadedImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Movie_MovieTheatreShow", Storage="_Movie", ThisKey="MovieId", OtherKey="Id", IsForeignKey=true)]
		public Movie Movie
		{
			get
			{
				return this._Movie.Entity;
			}
			set
			{
				Movie previousValue = this._Movie.Entity;
				if (((previousValue != value) 
							|| (this._Movie.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Movie.Entity = null;
						previousValue.MovieTheatreShows.Remove(this);
					}
					this._Movie.Entity = value;
					if ((value != null))
					{
						value.MovieTheatreShows.Add(this);
						this._MovieId = value.Id;
					}
					else
					{
						this._MovieId = default(long);
					}
					this.SendPropertyChanged("Movie");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Movie")]
	public partial class Movie : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private string _MovieName;
		
		private string _MovieCategory;
		
		private string _MovieRating;
		
		private string _MovieLanguage;
		
		private string _MovieContentType;
		
		private string _MovieType;
		
		private System.DateTime _CreatedOn;
		
		private long _CreatedBy;
		
		private System.Nullable<System.DateTime> _UpdatedOn;
		
		private System.Nullable<long> _UpdatedBy;
		
		private System.Nullable<System.DateTime> _DeletedOn;
		
		private System.Nullable<long> _DeletedBy;
		
		private bool _IsDeleted;
		
		private string _UploadedImage;
		
		private System.Nullable<bool> _IsActive;
		
		private string _AppDescription;
		
		private string _MobileImage;
		
		private EntitySet<MovieTheatreShow> _MovieTheatreShows;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnMovieNameChanging(string value);
    partial void OnMovieNameChanged();
    partial void OnMovieCategoryChanging(string value);
    partial void OnMovieCategoryChanged();
    partial void OnMovieRatingChanging(string value);
    partial void OnMovieRatingChanged();
    partial void OnMovieLanguageChanging(string value);
    partial void OnMovieLanguageChanged();
    partial void OnMovieContentTypeChanging(string value);
    partial void OnMovieContentTypeChanged();
    partial void OnMovieTypeChanging(string value);
    partial void OnMovieTypeChanged();
    partial void OnCreatedOnChanging(System.DateTime value);
    partial void OnCreatedOnChanged();
    partial void OnCreatedByChanging(long value);
    partial void OnCreatedByChanged();
    partial void OnUpdatedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdatedOnChanged();
    partial void OnUpdatedByChanging(System.Nullable<long> value);
    partial void OnUpdatedByChanged();
    partial void OnDeletedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnDeletedOnChanged();
    partial void OnDeletedByChanging(System.Nullable<long> value);
    partial void OnDeletedByChanged();
    partial void OnIsDeletedChanging(bool value);
    partial void OnIsDeletedChanged();
    partial void OnUploadedImageChanging(string value);
    partial void OnUploadedImageChanged();
    partial void OnIsActiveChanging(System.Nullable<bool> value);
    partial void OnIsActiveChanged();
    partial void OnAppDescriptionChanging(string value);
    partial void OnAppDescriptionChanged();
    partial void OnMobileImageChanging(string value);
    partial void OnMobileImageChanged();
    #endregion
		
		public Movie()
		{
			this._MovieTheatreShows = new EntitySet<MovieTheatreShow>(new Action<MovieTheatreShow>(this.attach_MovieTheatreShows), new Action<MovieTheatreShow>(this.detach_MovieTheatreShows));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MovieName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MovieName
		{
			get
			{
				return this._MovieName;
			}
			set
			{
				if ((this._MovieName != value))
				{
					this.OnMovieNameChanging(value);
					this.SendPropertyChanging();
					this._MovieName = value;
					this.SendPropertyChanged("MovieName");
					this.OnMovieNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MovieCategory", DbType="NVarChar(20)")]
		public string MovieCategory
		{
			get
			{
				return this._MovieCategory;
			}
			set
			{
				if ((this._MovieCategory != value))
				{
					this.OnMovieCategoryChanging(value);
					this.SendPropertyChanging();
					this._MovieCategory = value;
					this.SendPropertyChanged("MovieCategory");
					this.OnMovieCategoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MovieRating", DbType="NVarChar(5)")]
		public string MovieRating
		{
			get
			{
				return this._MovieRating;
			}
			set
			{
				if ((this._MovieRating != value))
				{
					this.OnMovieRatingChanging(value);
					this.SendPropertyChanging();
					this._MovieRating = value;
					this.SendPropertyChanged("MovieRating");
					this.OnMovieRatingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MovieLanguage", DbType="NVarChar(100)")]
		public string MovieLanguage
		{
			get
			{
				return this._MovieLanguage;
			}
			set
			{
				if ((this._MovieLanguage != value))
				{
					this.OnMovieLanguageChanging(value);
					this.SendPropertyChanging();
					this._MovieLanguage = value;
					this.SendPropertyChanged("MovieLanguage");
					this.OnMovieLanguageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MovieContentType", DbType="NVarChar(50)")]
		public string MovieContentType
		{
			get
			{
				return this._MovieContentType;
			}
			set
			{
				if ((this._MovieContentType != value))
				{
					this.OnMovieContentTypeChanging(value);
					this.SendPropertyChanging();
					this._MovieContentType = value;
					this.SendPropertyChanged("MovieContentType");
					this.OnMovieContentTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MovieType", DbType="NVarChar(50)")]
		public string MovieType
		{
			get
			{
				return this._MovieType;
			}
			set
			{
				if ((this._MovieType != value))
				{
					this.OnMovieTypeChanging(value);
					this.SendPropertyChanging();
					this._MovieType = value;
					this.SendPropertyChanged("MovieType");
					this.OnMovieTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOn", DbType="DateTime NOT NULL")]
		public System.DateTime CreatedOn
		{
			get
			{
				return this._CreatedOn;
			}
			set
			{
				if ((this._CreatedOn != value))
				{
					this.OnCreatedOnChanging(value);
					this.SendPropertyChanging();
					this._CreatedOn = value;
					this.SendPropertyChanged("CreatedOn");
					this.OnCreatedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="BigInt NOT NULL")]
		public long CreatedBy
		{
			get
			{
				return this._CreatedBy;
			}
			set
			{
				if ((this._CreatedBy != value))
				{
					this.OnCreatedByChanging(value);
					this.SendPropertyChanging();
					this._CreatedBy = value;
					this.SendPropertyChanged("CreatedBy");
					this.OnCreatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdatedOn
		{
			get
			{
				return this._UpdatedOn;
			}
			set
			{
				if ((this._UpdatedOn != value))
				{
					this.OnUpdatedOnChanging(value);
					this.SendPropertyChanging();
					this._UpdatedOn = value;
					this.SendPropertyChanged("UpdatedOn");
					this.OnUpdatedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedBy", DbType="BigInt")]
		public System.Nullable<long> UpdatedBy
		{
			get
			{
				return this._UpdatedBy;
			}
			set
			{
				if ((this._UpdatedBy != value))
				{
					this.OnUpdatedByChanging(value);
					this.SendPropertyChanging();
					this._UpdatedBy = value;
					this.SendPropertyChanged("UpdatedBy");
					this.OnUpdatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeletedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> DeletedOn
		{
			get
			{
				return this._DeletedOn;
			}
			set
			{
				if ((this._DeletedOn != value))
				{
					this.OnDeletedOnChanging(value);
					this.SendPropertyChanging();
					this._DeletedOn = value;
					this.SendPropertyChanged("DeletedOn");
					this.OnDeletedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeletedBy", DbType="BigInt")]
		public System.Nullable<long> DeletedBy
		{
			get
			{
				return this._DeletedBy;
			}
			set
			{
				if ((this._DeletedBy != value))
				{
					this.OnDeletedByChanging(value);
					this.SendPropertyChanging();
					this._DeletedBy = value;
					this.SendPropertyChanged("DeletedBy");
					this.OnDeletedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Bit NOT NULL")]
		public bool IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this.OnIsDeletedChanging(value);
					this.SendPropertyChanging();
					this._IsDeleted = value;
					this.SendPropertyChanged("IsDeleted");
					this.OnIsDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UploadedImage", DbType="VarChar(255)")]
		public string UploadedImage
		{
			get
			{
				return this._UploadedImage;
			}
			set
			{
				if ((this._UploadedImage != value))
				{
					this.OnUploadedImageChanging(value);
					this.SendPropertyChanging();
					this._UploadedImage = value;
					this.SendPropertyChanged("UploadedImage");
					this.OnUploadedImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit")]
		public System.Nullable<bool> IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this.OnIsActiveChanging(value);
					this.SendPropertyChanging();
					this._IsActive = value;
					this.SendPropertyChanged("IsActive");
					this.OnIsActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AppDescription", DbType="VarChar(250)")]
		public string AppDescription
		{
			get
			{
				return this._AppDescription;
			}
			set
			{
				if ((this._AppDescription != value))
				{
					this.OnAppDescriptionChanging(value);
					this.SendPropertyChanging();
					this._AppDescription = value;
					this.SendPropertyChanged("AppDescription");
					this.OnAppDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MobileImage", DbType="VarChar(50)")]
		public string MobileImage
		{
			get
			{
				return this._MobileImage;
			}
			set
			{
				if ((this._MobileImage != value))
				{
					this.OnMobileImageChanging(value);
					this.SendPropertyChanging();
					this._MobileImage = value;
					this.SendPropertyChanged("MobileImage");
					this.OnMobileImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Movie_MovieTheatreShow", Storage="_MovieTheatreShows", ThisKey="Id", OtherKey="MovieId")]
		public EntitySet<MovieTheatreShow> MovieTheatreShows
		{
			get
			{
				return this._MovieTheatreShows;
			}
			set
			{
				this._MovieTheatreShows.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_MovieTheatreShows(MovieTheatreShow entity)
		{
			this.SendPropertyChanging();
			entity.Movie = this;
		}
		
		private void detach_MovieTheatreShows(MovieTheatreShow entity)
		{
			this.SendPropertyChanging();
			entity.Movie = null;
		}
	}
	
	public partial class CountMovieResult
	{
		
		private System.Nullable<int> _Result;
		
		public CountMovieResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Result", DbType="Int")]
		public System.Nullable<int> Result
		{
			get
			{
				return this._Result;
			}
			set
			{
				if ((this._Result != value))
				{
					this._Result = value;
				}
			}
		}
	}
	
	public partial class CountMovieTheatreShowResult
	{
		
		private System.Nullable<int> _Result;
		
		public CountMovieTheatreShowResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Result", DbType="Int")]
		public System.Nullable<int> Result
		{
			get
			{
				return this._Result;
			}
			set
			{
				if ((this._Result != value))
				{
					this._Result = value;
				}
			}
		}
	}
	
	public partial class DeleteMovieResult
	{
		
		private int _TotalReference;
		
		private string _Name;
		
		public DeleteMovieResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalReference", DbType="Int NOT NULL")]
		public int TotalReference
		{
			get
			{
				return this._TotalReference;
			}
			set
			{
				if ((this._TotalReference != value))
				{
					this._TotalReference = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(MAX)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
	}
	
	public partial class DeleteMovieTheatreShowResult
	{
		
		private int _TotalReference;
		
		private string _Name;
		
		public DeleteMovieTheatreShowResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalReference", DbType="Int NOT NULL")]
		public int TotalReference
		{
			get
			{
				return this._TotalReference;
			}
			set
			{
				if ((this._TotalReference != value))
				{
					this._TotalReference = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(MAX)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
	}
	
	public partial class GetMovieAllResult
	{
		
		private long _Id;
		
		private string _MovieName;
		
		private string _MovieCategory;
		
		private string _MovieRating;
		
		private string _MovieLanguage;
		
		private string _MovieContentType;
		
		private string _MovieType;
		
		public GetMovieAllResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL")]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MovieName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MovieName
		{
			get
			{
				return this._MovieName;
			}
			set
			{
				if ((this._MovieName != value))
				{
					this._MovieName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MovieCategory", DbType="NVarChar(20)")]
		public string MovieCategory
		{
			get
			{
				return this._MovieCategory;
			}
			set
			{
				if ((this._MovieCategory != value))
				{
					this._MovieCategory = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MovieRating", DbType="NVarChar(5)")]
		public string MovieRating
		{
			get
			{
				return this._MovieRating;
			}
			set
			{
				if ((this._MovieRating != value))
				{
					this._MovieRating = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MovieLanguage", DbType="NVarChar(100)")]
		public string MovieLanguage
		{
			get
			{
				return this._MovieLanguage;
			}
			set
			{
				if ((this._MovieLanguage != value))
				{
					this._MovieLanguage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MovieContentType", DbType="NVarChar(50)")]
		public string MovieContentType
		{
			get
			{
				return this._MovieContentType;
			}
			set
			{
				if ((this._MovieContentType != value))
				{
					this._MovieContentType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MovieType", DbType="NVarChar(50)")]
		public string MovieType
		{
			get
			{
				return this._MovieType;
			}
			set
			{
				if ((this._MovieType != value))
				{
					this._MovieType = value;
				}
			}
		}
	}
	
	public partial class GetMovieTheatreShowByIdResult
	{
		
		private long _Id;
		
		private string _MovieTheatreShowName;
		
		private System.Nullable<System.DateTime> _ShowKeyDate;
		
		private System.Nullable<long> _MovieTheatreId;
		
		private System.Nullable<long> _MovieShowId;
		
		private long _MovieId;
		
		public GetMovieTheatreShowByIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL")]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MovieTheatreShowName", DbType="NVarChar(50)")]
		public string MovieTheatreShowName
		{
			get
			{
				return this._MovieTheatreShowName;
			}
			set
			{
				if ((this._MovieTheatreShowName != value))
				{
					this._MovieTheatreShowName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShowKeyDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ShowKeyDate
		{
			get
			{
				return this._ShowKeyDate;
			}
			set
			{
				if ((this._ShowKeyDate != value))
				{
					this._ShowKeyDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MovieTheatreId", DbType="BigInt")]
		public System.Nullable<long> MovieTheatreId
		{
			get
			{
				return this._MovieTheatreId;
			}
			set
			{
				if ((this._MovieTheatreId != value))
				{
					this._MovieTheatreId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MovieShowId", DbType="BigInt")]
		public System.Nullable<long> MovieShowId
		{
			get
			{
				return this._MovieShowId;
			}
			set
			{
				if ((this._MovieShowId != value))
				{
					this._MovieShowId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MovieId", DbType="BigInt NOT NULL")]
		public long MovieId
		{
			get
			{
				return this._MovieId;
			}
			set
			{
				if ((this._MovieId != value))
				{
					this._MovieId = value;
				}
			}
		}
	}
	
	public partial class SearchMovieTheatreShowResult
	{
		
		private System.Nullable<long> _RowNum;
		
		private System.Nullable<int> _Total;
		
		private long _Id;
		
		private string _MovieTheatreShowName;
		
		private System.Nullable<System.DateTime> _ShowKeyDate;
		
		private System.Nullable<long> _MovieTheatreId;
		
		private System.Nullable<long> _MovieShowId;
		
		private long _MovieId;
		
		private string _MovieName;
		
		public SearchMovieTheatreShowResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RowNum", DbType="BigInt")]
		public System.Nullable<long> RowNum
		{
			get
			{
				return this._RowNum;
			}
			set
			{
				if ((this._RowNum != value))
				{
					this._RowNum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", DbType="Int")]
		public System.Nullable<int> Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this._Total = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL")]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MovieTheatreShowName", DbType="NVarChar(50)")]
		public string MovieTheatreShowName
		{
			get
			{
				return this._MovieTheatreShowName;
			}
			set
			{
				if ((this._MovieTheatreShowName != value))
				{
					this._MovieTheatreShowName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShowKeyDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ShowKeyDate
		{
			get
			{
				return this._ShowKeyDate;
			}
			set
			{
				if ((this._ShowKeyDate != value))
				{
					this._ShowKeyDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MovieTheatreId", DbType="BigInt")]
		public System.Nullable<long> MovieTheatreId
		{
			get
			{
				return this._MovieTheatreId;
			}
			set
			{
				if ((this._MovieTheatreId != value))
				{
					this._MovieTheatreId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MovieShowId", DbType="BigInt")]
		public System.Nullable<long> MovieShowId
		{
			get
			{
				return this._MovieShowId;
			}
			set
			{
				if ((this._MovieShowId != value))
				{
					this._MovieShowId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MovieId", DbType="BigInt NOT NULL")]
		public long MovieId
		{
			get
			{
				return this._MovieId;
			}
			set
			{
				if ((this._MovieId != value))
				{
					this._MovieId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MovieName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MovieName
		{
			get
			{
				return this._MovieName;
			}
			set
			{
				if ((this._MovieName != value))
				{
					this._MovieName = value;
				}
			}
		}
	}
	
	public partial class InsertOrUpdateMovieTheatreShowResult
	{
		
		private long _InsertedId;
		
		public InsertOrUpdateMovieTheatreShowResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InsertedId", DbType="BigInt NOT NULL")]
		public long InsertedId
		{
			get
			{
				return this._InsertedId;
			}
			set
			{
				if ((this._InsertedId != value))
				{
					this._InsertedId = value;
				}
			}
		}
	}
	
	public partial class GetMovieTheatreShowByMovieIdResult
	{
		
		private long _Id;
		
		private string _MovieTheatreShowName;
		
		private System.Nullable<System.DateTime> _ShowKeyDate;
		
		private System.Nullable<long> _MovieTheatreId;
		
		private System.Nullable<long> _MovieShowId;
		
		private System.Nullable<decimal> _MemberAmount;
		
		private System.Nullable<decimal> _GuestAmount;
		
		private long _MovieId;
		
		private string _MovieName;
		
		public GetMovieTheatreShowByMovieIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL")]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MovieTheatreShowName", DbType="NVarChar(50)")]
		public string MovieTheatreShowName
		{
			get
			{
				return this._MovieTheatreShowName;
			}
			set
			{
				if ((this._MovieTheatreShowName != value))
				{
					this._MovieTheatreShowName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShowKeyDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ShowKeyDate
		{
			get
			{
				return this._ShowKeyDate;
			}
			set
			{
				if ((this._ShowKeyDate != value))
				{
					this._ShowKeyDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MovieTheatreId", DbType="BigInt")]
		public System.Nullable<long> MovieTheatreId
		{
			get
			{
				return this._MovieTheatreId;
			}
			set
			{
				if ((this._MovieTheatreId != value))
				{
					this._MovieTheatreId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MovieShowId", DbType="BigInt")]
		public System.Nullable<long> MovieShowId
		{
			get
			{
				return this._MovieShowId;
			}
			set
			{
				if ((this._MovieShowId != value))
				{
					this._MovieShowId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MemberAmount", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> MemberAmount
		{
			get
			{
				return this._MemberAmount;
			}
			set
			{
				if ((this._MemberAmount != value))
				{
					this._MemberAmount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GuestAmount", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> GuestAmount
		{
			get
			{
				return this._GuestAmount;
			}
			set
			{
				if ((this._GuestAmount != value))
				{
					this._GuestAmount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MovieId", DbType="BigInt NOT NULL")]
		public long MovieId
		{
			get
			{
				return this._MovieId;
			}
			set
			{
				if ((this._MovieId != value))
				{
					this._MovieId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MovieName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MovieName
		{
			get
			{
				return this._MovieName;
			}
			set
			{
				if ((this._MovieName != value))
				{
					this._MovieName = value;
				}
			}
		}
	}
	
	public partial class SearchMovieResult
	{
		
		private System.Nullable<long> _RowNum;
		
		private System.Nullable<int> _Total;
		
		private long _Id;
		
		private string _MovieName;
		
		private string _MovieCategory;
		
		private string _MovieRating;
		
		private string _MovieLanguage;
		
		private string _MovieContentType;
		
		private string _MovieType;
		
		public SearchMovieResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RowNum", DbType="BigInt")]
		public System.Nullable<long> RowNum
		{
			get
			{
				return this._RowNum;
			}
			set
			{
				if ((this._RowNum != value))
				{
					this._RowNum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", DbType="Int")]
		public System.Nullable<int> Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this._Total = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL")]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MovieName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MovieName
		{
			get
			{
				return this._MovieName;
			}
			set
			{
				if ((this._MovieName != value))
				{
					this._MovieName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MovieCategory", DbType="NVarChar(20)")]
		public string MovieCategory
		{
			get
			{
				return this._MovieCategory;
			}
			set
			{
				if ((this._MovieCategory != value))
				{
					this._MovieCategory = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MovieRating", DbType="NVarChar(5)")]
		public string MovieRating
		{
			get
			{
				return this._MovieRating;
			}
			set
			{
				if ((this._MovieRating != value))
				{
					this._MovieRating = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MovieLanguage", DbType="NVarChar(100)")]
		public string MovieLanguage
		{
			get
			{
				return this._MovieLanguage;
			}
			set
			{
				if ((this._MovieLanguage != value))
				{
					this._MovieLanguage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MovieContentType", DbType="NVarChar(50)")]
		public string MovieContentType
		{
			get
			{
				return this._MovieContentType;
			}
			set
			{
				if ((this._MovieContentType != value))
				{
					this._MovieContentType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MovieType", DbType="NVarChar(50)")]
		public string MovieType
		{
			get
			{
				return this._MovieType;
			}
			set
			{
				if ((this._MovieType != value))
				{
					this._MovieType = value;
				}
			}
		}
	}
	
	public partial class GetMovieShowForInActiveMovieResult
	{
		
		private System.Nullable<System.DateTime> _MovieShow;
		
		public GetMovieShowForInActiveMovieResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MovieShow", DbType="DateTime")]
		public System.Nullable<System.DateTime> MovieShow
		{
			get
			{
				return this._MovieShow;
			}
			set
			{
				if ((this._MovieShow != value))
				{
					this._MovieShow = value;
				}
			}
		}
	}
	
	public partial class GetMovieByIdResult
	{
		
		private long _Id;
		
		private string _MovieName;
		
		private string _MovieCategory;
		
		private string _MovieRating;
		
		private string _MovieLanguage;
		
		private string _MovieContentType;
		
		private string _MovieType;
		
		private string _UploadedImage;
		
		private System.Nullable<bool> _IsActive;
		
		private string _AppDescription;
		
		private string _MobileImage;
		
		private System.Nullable<int> _EntryAfter;
		
		private System.Nullable<int> _EntryBefore;
		
		public GetMovieByIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL")]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MovieName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MovieName
		{
			get
			{
				return this._MovieName;
			}
			set
			{
				if ((this._MovieName != value))
				{
					this._MovieName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MovieCategory", DbType="NVarChar(20)")]
		public string MovieCategory
		{
			get
			{
				return this._MovieCategory;
			}
			set
			{
				if ((this._MovieCategory != value))
				{
					this._MovieCategory = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MovieRating", DbType="NVarChar(5)")]
		public string MovieRating
		{
			get
			{
				return this._MovieRating;
			}
			set
			{
				if ((this._MovieRating != value))
				{
					this._MovieRating = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MovieLanguage", DbType="NVarChar(100)")]
		public string MovieLanguage
		{
			get
			{
				return this._MovieLanguage;
			}
			set
			{
				if ((this._MovieLanguage != value))
				{
					this._MovieLanguage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MovieContentType", DbType="NVarChar(50)")]
		public string MovieContentType
		{
			get
			{
				return this._MovieContentType;
			}
			set
			{
				if ((this._MovieContentType != value))
				{
					this._MovieContentType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MovieType", DbType="NVarChar(50)")]
		public string MovieType
		{
			get
			{
				return this._MovieType;
			}
			set
			{
				if ((this._MovieType != value))
				{
					this._MovieType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UploadedImage", DbType="VarChar(255)")]
		public string UploadedImage
		{
			get
			{
				return this._UploadedImage;
			}
			set
			{
				if ((this._UploadedImage != value))
				{
					this._UploadedImage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit")]
		public System.Nullable<bool> IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this._IsActive = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AppDescription", DbType="VarChar(250)")]
		public string AppDescription
		{
			get
			{
				return this._AppDescription;
			}
			set
			{
				if ((this._AppDescription != value))
				{
					this._AppDescription = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MobileImage", DbType="VarChar(50)")]
		public string MobileImage
		{
			get
			{
				return this._MobileImage;
			}
			set
			{
				if ((this._MobileImage != value))
				{
					this._MobileImage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntryAfter", DbType="Int")]
		public System.Nullable<int> EntryAfter
		{
			get
			{
				return this._EntryAfter;
			}
			set
			{
				if ((this._EntryAfter != value))
				{
					this._EntryAfter = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntryBefore", DbType="Int")]
		public System.Nullable<int> EntryBefore
		{
			get
			{
				return this._EntryBefore;
			}
			set
			{
				if ((this._EntryBefore != value))
				{
					this._EntryBefore = value;
				}
			}
		}
	}
	
	public partial class InsertOrUpdateMovieResult
	{
		
		private long _InsertedId;
		
		public InsertOrUpdateMovieResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InsertedId", DbType="BigInt NOT NULL")]
		public long InsertedId
		{
			get
			{
				return this._InsertedId;
			}
			set
			{
				if ((this._InsertedId != value))
				{
					this._InsertedId = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
