#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcubeWebPortalCMS.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name= "Karnavati_dba")]
	public partial class MovieTheatreDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertMovieTheatre(MovieTheatre instance);
    partial void UpdateMovieTheatre(MovieTheatre instance);
    partial void DeleteMovieTheatre(MovieTheatre instance);
    #endregion
		
		public MovieTheatreDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ECubeCMSConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MovieTheatreDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MovieTheatreDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MovieTheatreDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MovieTheatreDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<MovieTheatre> MovieTheatres
		{
			get
			{
				return this.GetTable<MovieTheatre>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetMovieTheatreAll")]
		public ISingleResult<GetMovieTheatreAllResult> GetMovieTheatreAll()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<GetMovieTheatreAllResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DeleteMovieTheatre")]
		public ISingleResult<DeleteMovieTheatreResult> DeleteMovieTheatre([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdList", DbType="NVarChar(MAX)")] string idlist, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DeletedBy", DbType="BigInt")] System.Nullable<long> deletedby, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageId", DbType="BigInt")] System.Nullable<long> pageid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idlist, deletedby, pageid);
			return ((ISingleResult<DeleteMovieTheatreResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CountMovieTheatre")]
		public ISingleResult<CountMovieTheatreResult> CountMovieTheatre()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<CountMovieTheatreResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SearchMovieTheatre")]
		public ISingleResult<SearchMovieTheatreResult> SearchMovieTheatre([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Rows", DbType="Int")] System.Nullable<int> rows, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Page", DbType="Int")] System.Nullable<int> page, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Search", DbType="NVarChar(500)")] string search, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Sort", DbType="NVarChar(50)")] string sort)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), rows, page, search, sort);
			return ((ISingleResult<SearchMovieTheatreResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CRM_Subservice")]
		public ISingleResult<CRM_SubserviceResult> CRM_Subservice()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<CRM_SubserviceResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CRM_GetServiceList")]
		public ISingleResult<CRM_GetServiceListResult> CRM_GetServiceList()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<CRM_GetServiceListResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetSubServiceByServiceIdandServiceFor")]
		public ISingleResult<GetSubServiceByServiceIdandServiceForResult> GetSubServiceByServiceIdandServiceFor([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ServiceId", DbType="Int")] System.Nullable<int> serviceId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ServiceFor", DbType="Int")] System.Nullable<int> serviceFor)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), serviceId, serviceFor);
			return ((ISingleResult<GetSubServiceByServiceIdandServiceForResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetMovieTheatreById")]
		public ISingleResult<GetMovieTheatreByIdResult> GetMovieTheatreById([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="BigInt")] System.Nullable<long> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((ISingleResult<GetMovieTheatreByIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UpdateMovieTheatreClassById")]
		public int UpdateMovieTheatreClassById([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="BigInt")] System.Nullable<long> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MemberSubServiceId", DbType="Int")] System.Nullable<int> memberSubServiceId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GuestSubServiceId", DbType="Int")] System.Nullable<int> guestSubServiceId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserId", DbType="BigInt")] System.Nullable<long> userId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageId", DbType="BigInt")] System.Nullable<long> pageId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, memberSubServiceId, guestSubServiceId, userId, pageId);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertOrUpdateMovieTheatre")]
		public ISingleResult<InsertOrUpdateMovieTheatreResult> InsertOrUpdateMovieTheatre([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="BigInt")] System.Nullable<long> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MovieTheatreName", DbType="VarChar(50)")] string movieTheatreName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TheatreFloor", DbType="VarChar(10)")] string theatreFloor, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserId", DbType="BigInt")] System.Nullable<long> userId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageId", DbType="BigInt")] System.Nullable<long> pageId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, movieTheatreName, theatreFloor, userId, pageId);
			return ((ISingleResult<InsertOrUpdateMovieTheatreResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetMovieTheatreClassByTheatreId")]
		public ISingleResult<GetMovieTheatreClassByTheatreIdResult> GetMovieTheatreClassByTheatreId([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TheatreId", DbType="Int")] System.Nullable<int> theatreId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MovieShowPeriodId", DbType="Int")] System.Nullable<int> movieShowPeriodId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), theatreId, movieShowPeriodId);
			return ((ISingleResult<GetMovieTheatreClassByTheatreIdResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MovieTheatre")]
	public partial class MovieTheatre : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private string _MovieTheatreName;
		
		private string _TheatreFloor;
		
		private System.DateTime _CreatedOn;
		
		private long _CreatedBy;
		
		private System.Nullable<System.DateTime> _UpdatedOn;
		
		private System.Nullable<long> _UpdatedBy;
		
		private System.Nullable<System.DateTime> _DeletedOn;
		
		private System.Nullable<long> _DeletedBy;
		
		private bool _IsDeleted;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnMovieTheatreNameChanging(string value);
    partial void OnMovieTheatreNameChanged();
    partial void OnTheatreFloorChanging(string value);
    partial void OnTheatreFloorChanged();
    partial void OnCreatedOnChanging(System.DateTime value);
    partial void OnCreatedOnChanged();
    partial void OnCreatedByChanging(long value);
    partial void OnCreatedByChanged();
    partial void OnUpdatedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdatedOnChanged();
    partial void OnUpdatedByChanging(System.Nullable<long> value);
    partial void OnUpdatedByChanged();
    partial void OnDeletedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnDeletedOnChanged();
    partial void OnDeletedByChanging(System.Nullable<long> value);
    partial void OnDeletedByChanged();
    partial void OnIsDeletedChanging(bool value);
    partial void OnIsDeletedChanged();
    #endregion
		
		public MovieTheatre()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MovieTheatreName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MovieTheatreName
		{
			get
			{
				return this._MovieTheatreName;
			}
			set
			{
				if ((this._MovieTheatreName != value))
				{
					this.OnMovieTheatreNameChanging(value);
					this.SendPropertyChanging();
					this._MovieTheatreName = value;
					this.SendPropertyChanged("MovieTheatreName");
					this.OnMovieTheatreNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TheatreFloor", DbType="VarChar(10)")]
		public string TheatreFloor
		{
			get
			{
				return this._TheatreFloor;
			}
			set
			{
				if ((this._TheatreFloor != value))
				{
					this.OnTheatreFloorChanging(value);
					this.SendPropertyChanging();
					this._TheatreFloor = value;
					this.SendPropertyChanged("TheatreFloor");
					this.OnTheatreFloorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOn", DbType="DateTime NOT NULL")]
		public System.DateTime CreatedOn
		{
			get
			{
				return this._CreatedOn;
			}
			set
			{
				if ((this._CreatedOn != value))
				{
					this.OnCreatedOnChanging(value);
					this.SendPropertyChanging();
					this._CreatedOn = value;
					this.SendPropertyChanged("CreatedOn");
					this.OnCreatedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="BigInt NOT NULL")]
		public long CreatedBy
		{
			get
			{
				return this._CreatedBy;
			}
			set
			{
				if ((this._CreatedBy != value))
				{
					this.OnCreatedByChanging(value);
					this.SendPropertyChanging();
					this._CreatedBy = value;
					this.SendPropertyChanged("CreatedBy");
					this.OnCreatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdatedOn
		{
			get
			{
				return this._UpdatedOn;
			}
			set
			{
				if ((this._UpdatedOn != value))
				{
					this.OnUpdatedOnChanging(value);
					this.SendPropertyChanging();
					this._UpdatedOn = value;
					this.SendPropertyChanged("UpdatedOn");
					this.OnUpdatedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedBy", DbType="BigInt")]
		public System.Nullable<long> UpdatedBy
		{
			get
			{
				return this._UpdatedBy;
			}
			set
			{
				if ((this._UpdatedBy != value))
				{
					this.OnUpdatedByChanging(value);
					this.SendPropertyChanging();
					this._UpdatedBy = value;
					this.SendPropertyChanged("UpdatedBy");
					this.OnUpdatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeletedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> DeletedOn
		{
			get
			{
				return this._DeletedOn;
			}
			set
			{
				if ((this._DeletedOn != value))
				{
					this.OnDeletedOnChanging(value);
					this.SendPropertyChanging();
					this._DeletedOn = value;
					this.SendPropertyChanged("DeletedOn");
					this.OnDeletedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeletedBy", DbType="BigInt")]
		public System.Nullable<long> DeletedBy
		{
			get
			{
				return this._DeletedBy;
			}
			set
			{
				if ((this._DeletedBy != value))
				{
					this.OnDeletedByChanging(value);
					this.SendPropertyChanging();
					this._DeletedBy = value;
					this.SendPropertyChanged("DeletedBy");
					this.OnDeletedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Bit NOT NULL")]
		public bool IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this.OnIsDeletedChanging(value);
					this.SendPropertyChanging();
					this._IsDeleted = value;
					this.SendPropertyChanged("IsDeleted");
					this.OnIsDeletedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class GetMovieTheatreAllResult
	{
		
		private long _Id;
		
		private string _MovieTheatreName;
		
		private string _TheatreFloor;
		
		public GetMovieTheatreAllResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL")]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MovieTheatreName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MovieTheatreName
		{
			get
			{
				return this._MovieTheatreName;
			}
			set
			{
				if ((this._MovieTheatreName != value))
				{
					this._MovieTheatreName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TheatreFloor", DbType="VarChar(10)")]
		public string TheatreFloor
		{
			get
			{
				return this._TheatreFloor;
			}
			set
			{
				if ((this._TheatreFloor != value))
				{
					this._TheatreFloor = value;
				}
			}
		}
	}
	
	public partial class DeleteMovieTheatreResult
	{
		
		private int _TotalReference;
		
		private string _Name;
		
		public DeleteMovieTheatreResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalReference", DbType="Int NOT NULL")]
		public int TotalReference
		{
			get
			{
				return this._TotalReference;
			}
			set
			{
				if ((this._TotalReference != value))
				{
					this._TotalReference = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
	}
	
	public partial class CountMovieTheatreResult
	{
		
		private int _Result;
		
		public CountMovieTheatreResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Result", DbType="Int NOT NULL")]
		public int Result
		{
			get
			{
				return this._Result;
			}
			set
			{
				if ((this._Result != value))
				{
					this._Result = value;
				}
			}
		}
	}
	
	public partial class SearchMovieTheatreResult
	{
		
		private System.Nullable<long> _RowNum;
		
		private System.Nullable<int> _Total;
		
		private long _Id;
		
		private string _MovieTheatreName;
		
		private string _TheatreFloor;
		
		public SearchMovieTheatreResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RowNum", DbType="BigInt")]
		public System.Nullable<long> RowNum
		{
			get
			{
				return this._RowNum;
			}
			set
			{
				if ((this._RowNum != value))
				{
					this._RowNum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", DbType="Int")]
		public System.Nullable<int> Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this._Total = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL")]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MovieTheatreName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MovieTheatreName
		{
			get
			{
				return this._MovieTheatreName;
			}
			set
			{
				if ((this._MovieTheatreName != value))
				{
					this._MovieTheatreName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TheatreFloor", DbType="VarChar(10)")]
		public string TheatreFloor
		{
			get
			{
				return this._TheatreFloor;
			}
			set
			{
				if ((this._TheatreFloor != value))
				{
					this._TheatreFloor = value;
				}
			}
		}
	}
	
	public partial class CRM_SubserviceResult
	{
		
		private decimal _Id;
		
		private string _Name;
		
		public CRM_SubserviceResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Decimal(18,0) NOT NULL")]
		public decimal Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(100)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
	}
	
	public partial class CRM_GetServiceListResult
	{
		
		private decimal _Id;
		
		private string _Name;
		
		private string _Colour;
		
		private System.Nullable<bool> _IsTaxFree;
		
		public CRM_GetServiceListResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Decimal(18,0) NOT NULL")]
		public decimal Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(100)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Colour", DbType="VarChar(50)")]
		public string Colour
		{
			get
			{
				return this._Colour;
			}
			set
			{
				if ((this._Colour != value))
				{
					this._Colour = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsTaxFree", DbType="Bit")]
		public System.Nullable<bool> IsTaxFree
		{
			get
			{
				return this._IsTaxFree;
			}
			set
			{
				if ((this._IsTaxFree != value))
				{
					this._IsTaxFree = value;
				}
			}
		}
	}
	
	public partial class GetSubServiceByServiceIdandServiceForResult
	{
		
		private decimal _Id;
		
		private string _Name;
		
		public GetSubServiceByServiceIdandServiceForResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Decimal(18,0) NOT NULL")]
		public decimal Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(100)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
	}
	
	public partial class GetMovieTheatreByIdResult
	{
		
		private long _Id;
		
		private string _MovieTheatreName;
		
		private string _TheatreFloor;
		
		private System.Nullable<long> _ServiceId;
		
		public GetMovieTheatreByIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL")]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MovieTheatreName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MovieTheatreName
		{
			get
			{
				return this._MovieTheatreName;
			}
			set
			{
				if ((this._MovieTheatreName != value))
				{
					this._MovieTheatreName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TheatreFloor", DbType="VarChar(10)")]
		public string TheatreFloor
		{
			get
			{
				return this._TheatreFloor;
			}
			set
			{
				if ((this._TheatreFloor != value))
				{
					this._TheatreFloor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ServiceId", DbType="BigInt")]
		public System.Nullable<long> ServiceId
		{
			get
			{
				return this._ServiceId;
			}
			set
			{
				if ((this._ServiceId != value))
				{
					this._ServiceId = value;
				}
			}
		}
	}
	
	public partial class InsertOrUpdateMovieTheatreResult
	{
		
		private long _InsertedId;
		
		public InsertOrUpdateMovieTheatreResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InsertedId", DbType="BigInt NOT NULL")]
		public long InsertedId
		{
			get
			{
				return this._InsertedId;
			}
			set
			{
				if ((this._InsertedId != value))
				{
					this._InsertedId = value;
				}
			}
		}
	}
	
	public partial class GetMovieTheatreClassByTheatreIdResult
	{
		
		private int _Id;
		
		private long _TheatreId;
		
		private string _ClassName;
		
		private string _ClassShorName;
		
		private string _ClassColor;
		
		private System.Nullable<int> _MemberSubServiceId;
		
		private System.Nullable<int> _GuestSubServiceId;
		
		private int _RateId;
		
		private decimal _MemberRate;
		
		private decimal _GuestRate;
		
		public GetMovieTheatreClassByTheatreIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TheatreId", DbType="BigInt NOT NULL")]
		public long TheatreId
		{
			get
			{
				return this._TheatreId;
			}
			set
			{
				if ((this._TheatreId != value))
				{
					this._TheatreId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClassName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ClassName
		{
			get
			{
				return this._ClassName;
			}
			set
			{
				if ((this._ClassName != value))
				{
					this._ClassName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClassShorName", DbType="VarChar(50)")]
		public string ClassShorName
		{
			get
			{
				return this._ClassShorName;
			}
			set
			{
				if ((this._ClassShorName != value))
				{
					this._ClassShorName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClassColor", DbType="VarChar(10)")]
		public string ClassColor
		{
			get
			{
				return this._ClassColor;
			}
			set
			{
				if ((this._ClassColor != value))
				{
					this._ClassColor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MemberSubServiceId", DbType="Int")]
		public System.Nullable<int> MemberSubServiceId
		{
			get
			{
				return this._MemberSubServiceId;
			}
			set
			{
				if ((this._MemberSubServiceId != value))
				{
					this._MemberSubServiceId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GuestSubServiceId", DbType="Int")]
		public System.Nullable<int> GuestSubServiceId
		{
			get
			{
				return this._GuestSubServiceId;
			}
			set
			{
				if ((this._GuestSubServiceId != value))
				{
					this._GuestSubServiceId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RateId", DbType="Int NOT NULL")]
		public int RateId
		{
			get
			{
				return this._RateId;
			}
			set
			{
				if ((this._RateId != value))
				{
					this._RateId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MemberRate", DbType="Decimal(18,4) NOT NULL")]
		public decimal MemberRate
		{
			get
			{
				return this._MemberRate;
			}
			set
			{
				if ((this._MemberRate != value))
				{
					this._MemberRate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GuestRate", DbType="Decimal(18,4) NOT NULL")]
		public decimal GuestRate
		{
			get
			{
				return this._GuestRate;
			}
			set
			{
				if ((this._GuestRate != value))
				{
					this._GuestRate = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
