#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcubeWebPortalCMS.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ClubO7_Dev")]
	public partial class MovieShowAssignDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public MovieShowAssignDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ECubeCMSConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MovieShowAssignDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MovieShowAssignDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MovieShowAssignDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MovieShowAssignDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<MovieShowPeriod> MovieShowPeriods
		{
			get
			{
				return this.GetTable<MovieShowPeriod>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MS_InsertorUpdateMovieShowPeriod")]
		public int MS_InsertorUpdateMovieShowPeriod([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StartDate", DbType="DateTime")] System.Nullable<System.DateTime> startDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EndDate", DbType="DateTime")] System.Nullable<System.DateTime> endDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CreatedBy", DbType="Int")] System.Nullable<int> createdBy)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, startDate, endDate, createdBy);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MS_DeleteMovieShowPeriod")]
		public int MS_DeleteMovieShowPeriod([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CreatedBy", DbType="Int")] System.Nullable<int> createdBy)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, createdBy);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MS_DeleteAssignMovieShows")]
		public ISingleResult<MS_DeleteAssignMovieShowsResult> MS_DeleteAssignMovieShows([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((ISingleResult<MS_DeleteAssignMovieShowsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MS_GetMovieShowDetailsByPeriodId")]
		public int MS_GetMovieShowDetailsByPeriodId([global::System.Data.Linq.Mapping.ParameterAttribute(Name="StartDate", DbType="DateTime")] System.Nullable<System.DateTime> startDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EndDate", DbType="DateTime")] System.Nullable<System.DateTime> endDate)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), startDate, endDate);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetMovieBookingCount")]
		public ISingleResult<GetMovieBookingCountResult> GetMovieBookingCount([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ShowId", DbType="Int")] System.Nullable<int> showId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), showId);
			return ((ISingleResult<GetMovieBookingCountResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CheckMovieExistByShowTime")]
		public ISingleResult<CheckMovieExistByShowTimeResult> CheckMovieExistByShowTime([global::System.Data.Linq.Mapping.ParameterAttribute(Name="StartDate", DbType="DateTime")] System.Nullable<System.DateTime> startDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EndDate", DbType="DateTime")] System.Nullable<System.DateTime> endDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MovieId", DbType="Int")] System.Nullable<int> movieId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TheatreId", DbType="Int")] System.Nullable<int> theatreId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ShowId", DbType="Int")] System.Nullable<int> showId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), startDate, endDate, movieId, theatreId, showId);
			return ((ISingleResult<CheckMovieExistByShowTimeResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MS_GetMovieShowPeriod")]
		public ISingleResult<MS_GetMovieShowPeriodResult> MS_GetMovieShowPeriod([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Rows", DbType="Int")] System.Nullable<int> rows, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Page", DbType="Int")] System.Nullable<int> page, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Search", DbType="NVarChar(500)")] string search, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Sort", DbType="NVarChar(50)")] string sort, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DisplayPastRecord", DbType="Bit")] System.Nullable<bool> displayPastRecord)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), rows, page, search, sort, displayPastRecord);
			return ((ISingleResult<MS_GetMovieShowPeriodResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MS_AssignMovieShows")]
		public ISingleResult<MS_AssignMovieShowsResult> MS_AssignMovieShows([global::System.Data.Linq.Mapping.ParameterAttribute(Name="XML", DbType="VarChar(MAX)")] string xML, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MovieTheatreId", DbType="Int")] System.Nullable<int> movieTheatreId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MovieShowPeriodId", DbType="Int")] System.Nullable<int> movieShowPeriodId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), xML, movieTheatreId, movieShowPeriodId);
			return ((ISingleResult<MS_AssignMovieShowsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SaveMovieShowRate")]
		public ISingleResult<SaveMovieShowRateResult> SaveMovieShowRate([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MovieShowPeriodId", DbType="Int")] System.Nullable<int> movieShowPeriodId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ClassId", DbType="Int")] System.Nullable<int> classId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MemberCMSRate", DbType="Decimal(18,4)")] System.Nullable<decimal> memberCMSRate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GuestCMSRate", DbType="Decimal(18,4)")] System.Nullable<decimal> guestCMSRate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserId", DbType="BigInt")] System.Nullable<long> userId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageId", DbType="BigInt")] System.Nullable<long> pageId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, movieShowPeriodId, classId, memberCMSRate, guestCMSRate, userId, pageId);
			return ((ISingleResult<SaveMovieShowRateResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MovieShowPeriod")]
	public partial class MovieShowPeriod
	{
		
		private int _id;
		
		private System.Nullable<System.DateTime> _StartDate;
		
		private System.Nullable<System.DateTime> _EndDate;
		
		private System.Nullable<System.DateTime> _CreatedOn;
		
		private System.Nullable<long> _CreatedBy;
		
		private System.Nullable<System.DateTime> _UpdatedOn;
		
		private System.Nullable<long> _UpdatedBy;
		
		private System.Nullable<System.DateTime> _DeletedOn;
		
		private System.Nullable<long> _DeletedBy;
		
		private System.Nullable<bool> _IsDeleted;
		
		private System.Nullable<int> _MovieTheatreId;
		
		private System.Nullable<System.DateTime> _DateToDisplay;
		
		private string _TimeToDisplay;
		
		public MovieShowPeriod()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> StartDate
		{
			get
			{
				return this._StartDate;
			}
			set
			{
				if ((this._StartDate != value))
				{
					this._StartDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> EndDate
		{
			get
			{
				return this._EndDate;
			}
			set
			{
				if ((this._EndDate != value))
				{
					this._EndDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this._CreatedOn;
			}
			set
			{
				if ((this._CreatedOn != value))
				{
					this._CreatedOn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="BigInt")]
		public System.Nullable<long> CreatedBy
		{
			get
			{
				return this._CreatedBy;
			}
			set
			{
				if ((this._CreatedBy != value))
				{
					this._CreatedBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdatedOn
		{
			get
			{
				return this._UpdatedOn;
			}
			set
			{
				if ((this._UpdatedOn != value))
				{
					this._UpdatedOn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedBy", DbType="BigInt")]
		public System.Nullable<long> UpdatedBy
		{
			get
			{
				return this._UpdatedBy;
			}
			set
			{
				if ((this._UpdatedBy != value))
				{
					this._UpdatedBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeletedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> DeletedOn
		{
			get
			{
				return this._DeletedOn;
			}
			set
			{
				if ((this._DeletedOn != value))
				{
					this._DeletedOn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeletedBy", DbType="BigInt")]
		public System.Nullable<long> DeletedBy
		{
			get
			{
				return this._DeletedBy;
			}
			set
			{
				if ((this._DeletedBy != value))
				{
					this._DeletedBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Bit")]
		public System.Nullable<bool> IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this._IsDeleted = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MovieTheatreId", DbType="Int")]
		public System.Nullable<int> MovieTheatreId
		{
			get
			{
				return this._MovieTheatreId;
			}
			set
			{
				if ((this._MovieTheatreId != value))
				{
					this._MovieTheatreId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateToDisplay", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateToDisplay
		{
			get
			{
				return this._DateToDisplay;
			}
			set
			{
				if ((this._DateToDisplay != value))
				{
					this._DateToDisplay = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeToDisplay", DbType="VarChar(50)")]
		public string TimeToDisplay
		{
			get
			{
				return this._TimeToDisplay;
			}
			set
			{
				if ((this._TimeToDisplay != value))
				{
					this._TimeToDisplay = value;
				}
			}
		}
	}
	
	public partial class MS_DeleteAssignMovieShowsResult
	{
		
		private string _Result;
		
		public MS_DeleteAssignMovieShowsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Result", DbType="VarChar(7) NOT NULL", CanBeNull=false)]
		public string Result
		{
			get
			{
				return this._Result;
			}
			set
			{
				if ((this._Result != value))
				{
					this._Result = value;
				}
			}
		}
	}
	
	public partial class GetMovieBookingCountResult
	{
		
		private System.Nullable<int> _BookingRecord;
		
		public GetMovieBookingCountResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookingRecord", DbType="Int")]
		public System.Nullable<int> BookingRecord
		{
			get
			{
				return this._BookingRecord;
			}
			set
			{
				if ((this._BookingRecord != value))
				{
					this._BookingRecord = value;
				}
			}
		}
	}
	
	public partial class CheckMovieExistByShowTimeResult
	{
		
		private System.Nullable<int> _ShowCount;
		
		public CheckMovieExistByShowTimeResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShowCount", DbType="Int")]
		public System.Nullable<int> ShowCount
		{
			get
			{
				return this._ShowCount;
			}
			set
			{
				if ((this._ShowCount != value))
				{
					this._ShowCount = value;
				}
			}
		}
	}
	
	public partial class MS_GetMovieShowPeriodResult
	{
		
		private System.Nullable<long> _RowNum;
		
		private System.Nullable<int> _Total;
		
		private int _id;
		
		private string _StartDate;
		
		private string _EndDate;
		
		private string _MovieTheatreName;
		
		private string _DateToDisplay;
		
		private string _TimeToDisplay;
		
		public MS_GetMovieShowPeriodResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RowNum", DbType="BigInt")]
		public System.Nullable<long> RowNum
		{
			get
			{
				return this._RowNum;
			}
			set
			{
				if ((this._RowNum != value))
				{
					this._RowNum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", DbType="Int")]
		public System.Nullable<int> Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this._Total = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartDate", DbType="VarChar(50)")]
		public string StartDate
		{
			get
			{
				return this._StartDate;
			}
			set
			{
				if ((this._StartDate != value))
				{
					this._StartDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndDate", DbType="VarChar(50)")]
		public string EndDate
		{
			get
			{
				return this._EndDate;
			}
			set
			{
				if ((this._EndDate != value))
				{
					this._EndDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MovieTheatreName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MovieTheatreName
		{
			get
			{
				return this._MovieTheatreName;
			}
			set
			{
				if ((this._MovieTheatreName != value))
				{
					this._MovieTheatreName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateToDisplay", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string DateToDisplay
		{
			get
			{
				return this._DateToDisplay;
			}
			set
			{
				if ((this._DateToDisplay != value))
				{
					this._DateToDisplay = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeToDisplay", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string TimeToDisplay
		{
			get
			{
				return this._TimeToDisplay;
			}
			set
			{
				if ((this._TimeToDisplay != value))
				{
					this._TimeToDisplay = value;
				}
			}
		}
	}
	
	public partial class MS_AssignMovieShowsResult
	{
		
		private int _MovieShowPeriodId;
		
		public MS_AssignMovieShowsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MovieShowPeriodId", DbType="Int NOT NULL")]
		public int MovieShowPeriodId
		{
			get
			{
				return this._MovieShowPeriodId;
			}
			set
			{
				if ((this._MovieShowPeriodId != value))
				{
					this._MovieShowPeriodId = value;
				}
			}
		}
	}
	
	public partial class SaveMovieShowRateResult
	{
		
		private int _InsertedId;
		
		public SaveMovieShowRateResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InsertedId", DbType="Int NOT NULL")]
		public int InsertedId
		{
			get
			{
				return this._InsertedId;
			}
			set
			{
				if ((this._InsertedId != value))
				{
					this._InsertedId = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
