#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcubeWebPortalCMS.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Karnavati_QC")]
	public partial class RoomBookingDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertRoomBooking(RoomBooking instance);
    partial void UpdateRoomBooking(RoomBooking instance);
    partial void DeleteRoomBooking(RoomBooking instance);
    partial void InsertRoomBookingDetail(RoomBookingDetail instance);
    partial void UpdateRoomBookingDetail(RoomBookingDetail instance);
    partial void DeleteRoomBookingDetail(RoomBookingDetail instance);
    partial void InsertRoomBookingGallary(RoomBookingGallary instance);
    partial void UpdateRoomBookingGallary(RoomBookingGallary instance);
    partial void DeleteRoomBookingGallary(RoomBookingGallary instance);
    #endregion
		
		public RoomBookingDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ECubeCMSConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public RoomBookingDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RoomBookingDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RoomBookingDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RoomBookingDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<RoomBooking> RoomBooking
		{
			get
			{
				return this.GetTable<RoomBooking>();
			}
		}
		
		public System.Data.Linq.Table<RoomBookingDetail> RoomBookingDetail
		{
			get
			{
				return this.GetTable<RoomBookingDetail>();
			}
		}
		
		public System.Data.Linq.Table<RoomBookingGallary> RoomBookingGallary
		{
			get
			{
				return this.GetTable<RoomBookingGallary>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MS_CountRoomBooking")]
		public ISingleResult<MS_CountRoomBookingResult> MS_CountRoomBooking()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<MS_CountRoomBookingResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MS_CountRoomBookingGallary")]
		public ISingleResult<MS_CountRoomBookingGallaryResult> MS_CountRoomBookingGallary()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<MS_CountRoomBookingGallaryResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MS_CountRoomBookingTextDetail")]
		public ISingleResult<MS_CountRoomBookingTextDetailResult> MS_CountRoomBookingTextDetail()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<MS_CountRoomBookingTextDetailResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MS_DeleteRoomBooking")]
		public ISingleResult<MS_DeleteRoomBookingResult> MS_DeleteRoomBooking([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdList", DbType="NVarChar(MAX)")] string idList, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DeletedBy", DbType="BigInt")] System.Nullable<long> deletedBy, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageId", DbType="BigInt")] System.Nullable<long> pageId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idList, deletedBy, pageId);
			return ((ISingleResult<MS_DeleteRoomBookingResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MS_DeleteRoomBookingGallary")]
		public ISingleResult<MS_DeleteRoomBookingGallaryResult> MS_DeleteRoomBookingGallary([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdList", DbType="NVarChar(MAX)")] string idList, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DeletedBy", DbType="BigInt")] System.Nullable<long> deletedBy, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageId", DbType="BigInt")] System.Nullable<long> pageId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idList, deletedBy, pageId);
			return ((ISingleResult<MS_DeleteRoomBookingGallaryResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MS_DeleteRoomBookingTextDetail")]
		public ISingleResult<MS_DeleteRoomBookingTextDetailResult> MS_DeleteRoomBookingTextDetail([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdList", DbType="NVarChar(MAX)")] string idList, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DeletedBy", DbType="BigInt")] System.Nullable<long> deletedBy, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageId", DbType="BigInt")] System.Nullable<long> pageId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idList, deletedBy, pageId);
			return ((ISingleResult<MS_DeleteRoomBookingTextDetailResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MS_GetRoomBookingGallaryAll")]
		public ISingleResult<MS_GetRoomBookingGallaryAllResult> MS_GetRoomBookingGallaryAll()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<MS_GetRoomBookingGallaryAllResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MS_GetRoomBookingGallaryById")]
		public ISingleResult<MS_GetRoomBookingGallaryByIdResult> MS_GetRoomBookingGallaryById([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="BigInt")] System.Nullable<long> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((ISingleResult<MS_GetRoomBookingGallaryByIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MS_GetRoomBookingGallaryByRoomBookingId")]
		public ISingleResult<MS_GetRoomBookingGallaryByRoomBookingIdResult> MS_GetRoomBookingGallaryByRoomBookingId([global::System.Data.Linq.Mapping.ParameterAttribute(Name="RoomBookingId", DbType="BigInt")] System.Nullable<long> roomBookingId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), roomBookingId);
			return ((ISingleResult<MS_GetRoomBookingGallaryByRoomBookingIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MS_GetRoomBookingTextDetailById")]
		public ISingleResult<MS_GetRoomBookingTextDetailByIdResult> MS_GetRoomBookingTextDetailById([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="BigInt")] System.Nullable<long> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((ISingleResult<MS_GetRoomBookingTextDetailByIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MS_GetRoomBookingTextDetailByRoomBookingId")]
		public ISingleResult<MS_GetRoomBookingTextDetailByRoomBookingIdResult> MS_GetRoomBookingTextDetailByRoomBookingId([global::System.Data.Linq.Mapping.ParameterAttribute(Name="RoomBookingId", DbType="BigInt")] System.Nullable<long> roomBookingId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), roomBookingId);
			return ((ISingleResult<MS_GetRoomBookingTextDetailByRoomBookingIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MS_GetRoomBookinTextDetailAll", IsComposable=true)]
		public object MS_GetRoomBookinTextDetailAll()
		{
			return ((object)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod()))).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MS_GetRoomGallaryByRoomBookingId")]
		public ISingleResult<MS_GetRoomGallaryByRoomBookingIdResult> MS_GetRoomGallaryByRoomBookingId([global::System.Data.Linq.Mapping.ParameterAttribute(Name="RoomBookingId", DbType="BigInt")] System.Nullable<long> roomBookingId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), roomBookingId);
			return ((ISingleResult<MS_GetRoomGallaryByRoomBookingIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MS_InsertOrUpdateRoomBookingGallary")]
		public ISingleResult<MS_InsertOrUpdateRoomBookingGallaryResult> MS_InsertOrUpdateRoomBookingGallary([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="BigInt")] System.Nullable<long> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RoomBookingId", DbType="BigInt")] System.Nullable<long> roomBookingId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GallaryImage", DbType="NVarChar(200)")] string gallaryImage, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserId", DbType="BigInt")] System.Nullable<long> userId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageId", DbType="BigInt")] System.Nullable<long> pageId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, roomBookingId, gallaryImage, userId, pageId);
			return ((ISingleResult<MS_InsertOrUpdateRoomBookingGallaryResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MS_InsertOrUpdateRoomBookingTextDetail")]
		public ISingleResult<MS_InsertOrUpdateRoomBookingTextDetailResult> MS_InsertOrUpdateRoomBookingTextDetail([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="BigInt")] System.Nullable<long> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RoomBookingId", DbType="BigInt")] System.Nullable<long> roomBookingId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TaxPercentage", DbType="Decimal(10,2)")] System.Nullable<decimal> taxPercentage, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TaxDescription", DbType="NVarChar(200)")] string taxDescription, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserId", DbType="BigInt")] System.Nullable<long> userId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageId", DbType="BigInt")] System.Nullable<long> pageId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, roomBookingId, taxPercentage, taxDescription, userId, pageId);
			return ((ISingleResult<MS_InsertOrUpdateRoomBookingTextDetailResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MS_SearchRoomBookingDetail")]
		public ISingleResult<MS_SearchRoomBookingDetailResult> MS_SearchRoomBookingDetail([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Rows", DbType="Int")] System.Nullable<int> rows, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Page", DbType="Int")] System.Nullable<int> page, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Search", DbType="NVarChar(500)")] string search, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Sort", DbType="NVarChar(50)")] string sort)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), rows, page, search, sort);
			return ((ISingleResult<MS_SearchRoomBookingDetailResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MS_SearchRoomBookingGallary")]
		public ISingleResult<MS_SearchRoomBookingGallaryResult> MS_SearchRoomBookingGallary([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Rows", DbType="Int")] System.Nullable<int> rows, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Page", DbType="Int")] System.Nullable<int> page, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Search", DbType="NVarChar(500)")] string search, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Sort", DbType="NVarChar(50)")] string sort)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), rows, page, search, sort);
			return ((ISingleResult<MS_SearchRoomBookingGallaryResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MS_GetRoomBookingAll")]
		public ISingleResult<MS_GetRoomBookingAllResult> MS_GetRoomBookingAll()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<MS_GetRoomBookingAllResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MS_GetRoomBookingById")]
		public ISingleResult<MS_GetRoomBookingByIdResult> MS_GetRoomBookingById([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="BigInt")] System.Nullable<long> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((ISingleResult<MS_GetRoomBookingByIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MS_InsertOrUpdateRoomBooking")]
		public ISingleResult<MS_InsertOrUpdateRoomBookingResult> MS_InsertOrUpdateRoomBooking([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="BigInt")] System.Nullable<long> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RoomBookingName", DbType="NVarChar(200)")] string roomBookingName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Description", DbType="NVarChar(MAX)")] string description, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Member", DbType="Decimal(10,2)")] System.Nullable<decimal> member, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Guest", DbType="Decimal(10,2)")] System.Nullable<decimal> guest, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProfilePic", DbType="NVarChar(200)")] string profilePic, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Terms", DbType="NVarChar(200)")] string terms, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserId", DbType="BigInt")] System.Nullable<long> userId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageId", DbType="BigInt")] System.Nullable<long> pageId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, roomBookingName, description, member, guest, profilePic, terms, userId, pageId);
			return ((ISingleResult<MS_InsertOrUpdateRoomBookingResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MS_SearchRoomBooking")]
		public ISingleResult<MS_SearchRoomBookingResult> MS_SearchRoomBooking([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Rows", DbType="Int")] System.Nullable<int> rows, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Page", DbType="Int")] System.Nullable<int> page, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Search", DbType="NVarChar(500)")] string search, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Sort", DbType="NVarChar(50)")] string sort)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), rows, page, search, sort);
			return ((ISingleResult<MS_SearchRoomBookingResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RoomBooking")]
	public partial class RoomBooking : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private string _RoomBookingName;
		
		private string _Description;
		
		private System.Nullable<decimal> _Member;
		
		private System.Nullable<decimal> _Guest;
		
		private string _ProfilePic;
		
		private System.DateTime _CreatedOn;
		
		private long _CreatedBy;
		
		private System.Nullable<System.DateTime> _UpdatedOn;
		
		private System.Nullable<long> _UpdatedBy;
		
		private System.Nullable<System.DateTime> _DeletedOn;
		
		private System.Nullable<long> _DeletedBy;
		
		private bool _IsDeleted;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnRoomBookingNameChanging(string value);
    partial void OnRoomBookingNameChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnMemberChanging(System.Nullable<decimal> value);
    partial void OnMemberChanged();
    partial void OnGuestChanging(System.Nullable<decimal> value);
    partial void OnGuestChanged();
    partial void OnProfilePicChanging(string value);
    partial void OnProfilePicChanged();
    partial void OnCreatedOnChanging(System.DateTime value);
    partial void OnCreatedOnChanged();
    partial void OnCreatedByChanging(long value);
    partial void OnCreatedByChanged();
    partial void OnUpdatedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdatedOnChanged();
    partial void OnUpdatedByChanging(System.Nullable<long> value);
    partial void OnUpdatedByChanged();
    partial void OnDeletedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnDeletedOnChanged();
    partial void OnDeletedByChanging(System.Nullable<long> value);
    partial void OnDeletedByChanged();
    partial void OnIsDeletedChanging(bool value);
    partial void OnIsDeletedChanged();
    #endregion
		
		public RoomBooking()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoomBookingName", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string RoomBookingName
		{
			get
			{
				return this._RoomBookingName;
			}
			set
			{
				if ((this._RoomBookingName != value))
				{
					this.OnRoomBookingNameChanging(value);
					this.SendPropertyChanging();
					this._RoomBookingName = value;
					this.SendPropertyChanged("RoomBookingName");
					this.OnRoomBookingNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(MAX)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Member", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Member
		{
			get
			{
				return this._Member;
			}
			set
			{
				if ((this._Member != value))
				{
					this.OnMemberChanging(value);
					this.SendPropertyChanging();
					this._Member = value;
					this.SendPropertyChanged("Member");
					this.OnMemberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Guest", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Guest
		{
			get
			{
				return this._Guest;
			}
			set
			{
				if ((this._Guest != value))
				{
					this.OnGuestChanging(value);
					this.SendPropertyChanging();
					this._Guest = value;
					this.SendPropertyChanged("Guest");
					this.OnGuestChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProfilePic", DbType="NVarChar(200)")]
		public string ProfilePic
		{
			get
			{
				return this._ProfilePic;
			}
			set
			{
				if ((this._ProfilePic != value))
				{
					this.OnProfilePicChanging(value);
					this.SendPropertyChanging();
					this._ProfilePic = value;
					this.SendPropertyChanged("ProfilePic");
					this.OnProfilePicChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOn", DbType="DateTime NOT NULL")]
		public System.DateTime CreatedOn
		{
			get
			{
				return this._CreatedOn;
			}
			set
			{
				if ((this._CreatedOn != value))
				{
					this.OnCreatedOnChanging(value);
					this.SendPropertyChanging();
					this._CreatedOn = value;
					this.SendPropertyChanged("CreatedOn");
					this.OnCreatedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="BigInt NOT NULL")]
		public long CreatedBy
		{
			get
			{
				return this._CreatedBy;
			}
			set
			{
				if ((this._CreatedBy != value))
				{
					this.OnCreatedByChanging(value);
					this.SendPropertyChanging();
					this._CreatedBy = value;
					this.SendPropertyChanged("CreatedBy");
					this.OnCreatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdatedOn
		{
			get
			{
				return this._UpdatedOn;
			}
			set
			{
				if ((this._UpdatedOn != value))
				{
					this.OnUpdatedOnChanging(value);
					this.SendPropertyChanging();
					this._UpdatedOn = value;
					this.SendPropertyChanged("UpdatedOn");
					this.OnUpdatedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedBy", DbType="BigInt")]
		public System.Nullable<long> UpdatedBy
		{
			get
			{
				return this._UpdatedBy;
			}
			set
			{
				if ((this._UpdatedBy != value))
				{
					this.OnUpdatedByChanging(value);
					this.SendPropertyChanging();
					this._UpdatedBy = value;
					this.SendPropertyChanged("UpdatedBy");
					this.OnUpdatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeletedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> DeletedOn
		{
			get
			{
				return this._DeletedOn;
			}
			set
			{
				if ((this._DeletedOn != value))
				{
					this.OnDeletedOnChanging(value);
					this.SendPropertyChanging();
					this._DeletedOn = value;
					this.SendPropertyChanged("DeletedOn");
					this.OnDeletedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeletedBy", DbType="BigInt")]
		public System.Nullable<long> DeletedBy
		{
			get
			{
				return this._DeletedBy;
			}
			set
			{
				if ((this._DeletedBy != value))
				{
					this.OnDeletedByChanging(value);
					this.SendPropertyChanging();
					this._DeletedBy = value;
					this.SendPropertyChanged("DeletedBy");
					this.OnDeletedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Bit NOT NULL")]
		public bool IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this.OnIsDeletedChanging(value);
					this.SendPropertyChanging();
					this._IsDeleted = value;
					this.SendPropertyChanged("IsDeleted");
					this.OnIsDeletedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RoomBookingDetail")]
	public partial class RoomBookingDetail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private System.Nullable<long> _RoomBookingId;
		
		private System.Nullable<decimal> _TaxPercentage;
		
		private string _TaxDescription;
		
		private System.DateTime _CreatedOn;
		
		private long _CreatedBy;
		
		private System.Nullable<System.DateTime> _UpdatedOn;
		
		private System.Nullable<long> _UpdatedBy;
		
		private System.Nullable<System.DateTime> _DeletedOn;
		
		private System.Nullable<long> _DeletedBy;
		
		private bool _IsDeleted;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnRoomBookingIdChanging(System.Nullable<long> value);
    partial void OnRoomBookingIdChanged();
    partial void OnTaxPercentageChanging(System.Nullable<decimal> value);
    partial void OnTaxPercentageChanged();
    partial void OnTaxDescriptionChanging(string value);
    partial void OnTaxDescriptionChanged();
    partial void OnCreatedOnChanging(System.DateTime value);
    partial void OnCreatedOnChanged();
    partial void OnCreatedByChanging(long value);
    partial void OnCreatedByChanged();
    partial void OnUpdatedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdatedOnChanged();
    partial void OnUpdatedByChanging(System.Nullable<long> value);
    partial void OnUpdatedByChanged();
    partial void OnDeletedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnDeletedOnChanged();
    partial void OnDeletedByChanging(System.Nullable<long> value);
    partial void OnDeletedByChanged();
    partial void OnIsDeletedChanging(bool value);
    partial void OnIsDeletedChanged();
    #endregion
		
		public RoomBookingDetail()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoomBookingId", DbType="BigInt")]
		public System.Nullable<long> RoomBookingId
		{
			get
			{
				return this._RoomBookingId;
			}
			set
			{
				if ((this._RoomBookingId != value))
				{
					this.OnRoomBookingIdChanging(value);
					this.SendPropertyChanging();
					this._RoomBookingId = value;
					this.SendPropertyChanged("RoomBookingId");
					this.OnRoomBookingIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxPercentage", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> TaxPercentage
		{
			get
			{
				return this._TaxPercentage;
			}
			set
			{
				if ((this._TaxPercentage != value))
				{
					this.OnTaxPercentageChanging(value);
					this.SendPropertyChanging();
					this._TaxPercentage = value;
					this.SendPropertyChanged("TaxPercentage");
					this.OnTaxPercentageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxDescription", DbType="NVarChar(200)")]
		public string TaxDescription
		{
			get
			{
				return this._TaxDescription;
			}
			set
			{
				if ((this._TaxDescription != value))
				{
					this.OnTaxDescriptionChanging(value);
					this.SendPropertyChanging();
					this._TaxDescription = value;
					this.SendPropertyChanged("TaxDescription");
					this.OnTaxDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOn", DbType="DateTime NOT NULL")]
		public System.DateTime CreatedOn
		{
			get
			{
				return this._CreatedOn;
			}
			set
			{
				if ((this._CreatedOn != value))
				{
					this.OnCreatedOnChanging(value);
					this.SendPropertyChanging();
					this._CreatedOn = value;
					this.SendPropertyChanged("CreatedOn");
					this.OnCreatedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="BigInt NOT NULL")]
		public long CreatedBy
		{
			get
			{
				return this._CreatedBy;
			}
			set
			{
				if ((this._CreatedBy != value))
				{
					this.OnCreatedByChanging(value);
					this.SendPropertyChanging();
					this._CreatedBy = value;
					this.SendPropertyChanged("CreatedBy");
					this.OnCreatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdatedOn
		{
			get
			{
				return this._UpdatedOn;
			}
			set
			{
				if ((this._UpdatedOn != value))
				{
					this.OnUpdatedOnChanging(value);
					this.SendPropertyChanging();
					this._UpdatedOn = value;
					this.SendPropertyChanged("UpdatedOn");
					this.OnUpdatedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedBy", DbType="BigInt")]
		public System.Nullable<long> UpdatedBy
		{
			get
			{
				return this._UpdatedBy;
			}
			set
			{
				if ((this._UpdatedBy != value))
				{
					this.OnUpdatedByChanging(value);
					this.SendPropertyChanging();
					this._UpdatedBy = value;
					this.SendPropertyChanged("UpdatedBy");
					this.OnUpdatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeletedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> DeletedOn
		{
			get
			{
				return this._DeletedOn;
			}
			set
			{
				if ((this._DeletedOn != value))
				{
					this.OnDeletedOnChanging(value);
					this.SendPropertyChanging();
					this._DeletedOn = value;
					this.SendPropertyChanged("DeletedOn");
					this.OnDeletedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeletedBy", DbType="BigInt")]
		public System.Nullable<long> DeletedBy
		{
			get
			{
				return this._DeletedBy;
			}
			set
			{
				if ((this._DeletedBy != value))
				{
					this.OnDeletedByChanging(value);
					this.SendPropertyChanging();
					this._DeletedBy = value;
					this.SendPropertyChanged("DeletedBy");
					this.OnDeletedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Bit NOT NULL")]
		public bool IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this.OnIsDeletedChanging(value);
					this.SendPropertyChanging();
					this._IsDeleted = value;
					this.SendPropertyChanged("IsDeleted");
					this.OnIsDeletedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RoomBookingGallary")]
	public partial class RoomBookingGallary : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private System.Nullable<long> _RoomBookingId;
		
		private string _GallaryImage;
		
		private System.DateTime _CreatedOn;
		
		private long _CreatedBy;
		
		private System.Nullable<System.DateTime> _UpdatedOn;
		
		private System.Nullable<long> _UpdatedBy;
		
		private System.Nullable<System.DateTime> _DeletedOn;
		
		private System.Nullable<long> _DeletedBy;
		
		private bool _IsDeleted;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnRoomBookingIdChanging(System.Nullable<long> value);
    partial void OnRoomBookingIdChanged();
    partial void OnGallaryImageChanging(string value);
    partial void OnGallaryImageChanged();
    partial void OnCreatedOnChanging(System.DateTime value);
    partial void OnCreatedOnChanged();
    partial void OnCreatedByChanging(long value);
    partial void OnCreatedByChanged();
    partial void OnUpdatedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdatedOnChanged();
    partial void OnUpdatedByChanging(System.Nullable<long> value);
    partial void OnUpdatedByChanged();
    partial void OnDeletedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnDeletedOnChanged();
    partial void OnDeletedByChanging(System.Nullable<long> value);
    partial void OnDeletedByChanged();
    partial void OnIsDeletedChanging(bool value);
    partial void OnIsDeletedChanged();
    #endregion
		
		public RoomBookingGallary()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoomBookingId", DbType="BigInt")]
		public System.Nullable<long> RoomBookingId
		{
			get
			{
				return this._RoomBookingId;
			}
			set
			{
				if ((this._RoomBookingId != value))
				{
					this.OnRoomBookingIdChanging(value);
					this.SendPropertyChanging();
					this._RoomBookingId = value;
					this.SendPropertyChanged("RoomBookingId");
					this.OnRoomBookingIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GallaryImage", DbType="NVarChar(200)")]
		public string GallaryImage
		{
			get
			{
				return this._GallaryImage;
			}
			set
			{
				if ((this._GallaryImage != value))
				{
					this.OnGallaryImageChanging(value);
					this.SendPropertyChanging();
					this._GallaryImage = value;
					this.SendPropertyChanged("GallaryImage");
					this.OnGallaryImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOn", DbType="DateTime NOT NULL")]
		public System.DateTime CreatedOn
		{
			get
			{
				return this._CreatedOn;
			}
			set
			{
				if ((this._CreatedOn != value))
				{
					this.OnCreatedOnChanging(value);
					this.SendPropertyChanging();
					this._CreatedOn = value;
					this.SendPropertyChanged("CreatedOn");
					this.OnCreatedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="BigInt NOT NULL")]
		public long CreatedBy
		{
			get
			{
				return this._CreatedBy;
			}
			set
			{
				if ((this._CreatedBy != value))
				{
					this.OnCreatedByChanging(value);
					this.SendPropertyChanging();
					this._CreatedBy = value;
					this.SendPropertyChanged("CreatedBy");
					this.OnCreatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdatedOn
		{
			get
			{
				return this._UpdatedOn;
			}
			set
			{
				if ((this._UpdatedOn != value))
				{
					this.OnUpdatedOnChanging(value);
					this.SendPropertyChanging();
					this._UpdatedOn = value;
					this.SendPropertyChanged("UpdatedOn");
					this.OnUpdatedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedBy", DbType="BigInt")]
		public System.Nullable<long> UpdatedBy
		{
			get
			{
				return this._UpdatedBy;
			}
			set
			{
				if ((this._UpdatedBy != value))
				{
					this.OnUpdatedByChanging(value);
					this.SendPropertyChanging();
					this._UpdatedBy = value;
					this.SendPropertyChanged("UpdatedBy");
					this.OnUpdatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeletedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> DeletedOn
		{
			get
			{
				return this._DeletedOn;
			}
			set
			{
				if ((this._DeletedOn != value))
				{
					this.OnDeletedOnChanging(value);
					this.SendPropertyChanging();
					this._DeletedOn = value;
					this.SendPropertyChanged("DeletedOn");
					this.OnDeletedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeletedBy", DbType="BigInt")]
		public System.Nullable<long> DeletedBy
		{
			get
			{
				return this._DeletedBy;
			}
			set
			{
				if ((this._DeletedBy != value))
				{
					this.OnDeletedByChanging(value);
					this.SendPropertyChanging();
					this._DeletedBy = value;
					this.SendPropertyChanged("DeletedBy");
					this.OnDeletedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Bit NOT NULL")]
		public bool IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this.OnIsDeletedChanging(value);
					this.SendPropertyChanging();
					this._IsDeleted = value;
					this.SendPropertyChanged("IsDeleted");
					this.OnIsDeletedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class MS_CountRoomBookingResult
	{
		
		private System.Nullable<int> _Result;
		
		public MS_CountRoomBookingResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Result", DbType="Int")]
		public System.Nullable<int> Result
		{
			get
			{
				return this._Result;
			}
			set
			{
				if ((this._Result != value))
				{
					this._Result = value;
				}
			}
		}
	}
	
	public partial class MS_CountRoomBookingGallaryResult
	{
		
		private System.Nullable<int> _Result;
		
		public MS_CountRoomBookingGallaryResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Result", DbType="Int")]
		public System.Nullable<int> Result
		{
			get
			{
				return this._Result;
			}
			set
			{
				if ((this._Result != value))
				{
					this._Result = value;
				}
			}
		}
	}
	
	public partial class MS_CountRoomBookingTextDetailResult
	{
		
		private System.Nullable<int> _Result;
		
		public MS_CountRoomBookingTextDetailResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Result", DbType="Int")]
		public System.Nullable<int> Result
		{
			get
			{
				return this._Result;
			}
			set
			{
				if ((this._Result != value))
				{
					this._Result = value;
				}
			}
		}
	}
	
	public partial class MS_DeleteRoomBookingResult
	{
		
		private int _TotalReference;
		
		private string _Name;
		
		public MS_DeleteRoomBookingResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalReference", DbType="Int NOT NULL")]
		public int TotalReference
		{
			get
			{
				return this._TotalReference;
			}
			set
			{
				if ((this._TotalReference != value))
				{
					this._TotalReference = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(MAX)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
	}
	
	public partial class MS_DeleteRoomBookingGallaryResult
	{
		
		private int _TotalReference;
		
		private string _Name;
		
		public MS_DeleteRoomBookingGallaryResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalReference", DbType="Int NOT NULL")]
		public int TotalReference
		{
			get
			{
				return this._TotalReference;
			}
			set
			{
				if ((this._TotalReference != value))
				{
					this._TotalReference = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(MAX)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
	}
	
	public partial class MS_DeleteRoomBookingTextDetailResult
	{
		
		private int _TotalReference;
		
		private string _Name;
		
		public MS_DeleteRoomBookingTextDetailResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalReference", DbType="Int NOT NULL")]
		public int TotalReference
		{
			get
			{
				return this._TotalReference;
			}
			set
			{
				if ((this._TotalReference != value))
				{
					this._TotalReference = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(MAX)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
	}
	
	public partial class MS_GetRoomBookingGallaryAllResult
	{
		
		private long _Id;
		
		private System.Nullable<long> _RoomBookingId;
		
		private string _RoomBookingName;
		
		private string _GallaryImage;
		
		public MS_GetRoomBookingGallaryAllResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL")]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoomBookingId", DbType="BigInt")]
		public System.Nullable<long> RoomBookingId
		{
			get
			{
				return this._RoomBookingId;
			}
			set
			{
				if ((this._RoomBookingId != value))
				{
					this._RoomBookingId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoomBookingName", DbType="NVarChar(200)")]
		public string RoomBookingName
		{
			get
			{
				return this._RoomBookingName;
			}
			set
			{
				if ((this._RoomBookingName != value))
				{
					this._RoomBookingName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GallaryImage", DbType="NVarChar(200)")]
		public string GallaryImage
		{
			get
			{
				return this._GallaryImage;
			}
			set
			{
				if ((this._GallaryImage != value))
				{
					this._GallaryImage = value;
				}
			}
		}
	}
	
	public partial class MS_GetRoomBookingGallaryByIdResult
	{
		
		private long _Id;
		
		private System.Nullable<long> _RoomBookingId;
		
		private string _GallaryImage;
		
		public MS_GetRoomBookingGallaryByIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL")]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoomBookingId", DbType="BigInt")]
		public System.Nullable<long> RoomBookingId
		{
			get
			{
				return this._RoomBookingId;
			}
			set
			{
				if ((this._RoomBookingId != value))
				{
					this._RoomBookingId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GallaryImage", DbType="NVarChar(200)")]
		public string GallaryImage
		{
			get
			{
				return this._GallaryImage;
			}
			set
			{
				if ((this._GallaryImage != value))
				{
					this._GallaryImage = value;
				}
			}
		}
	}
	
	public partial class MS_GetRoomBookingGallaryByRoomBookingIdResult
	{
		
		private long _Id;
		
		private System.Nullable<long> _RoomBookingId;
		
		private string _RoomBookingName;
		
		private string _GallaryImage;
		
		public MS_GetRoomBookingGallaryByRoomBookingIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL")]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoomBookingId", DbType="BigInt")]
		public System.Nullable<long> RoomBookingId
		{
			get
			{
				return this._RoomBookingId;
			}
			set
			{
				if ((this._RoomBookingId != value))
				{
					this._RoomBookingId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoomBookingName", DbType="NVarChar(200)")]
		public string RoomBookingName
		{
			get
			{
				return this._RoomBookingName;
			}
			set
			{
				if ((this._RoomBookingName != value))
				{
					this._RoomBookingName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GallaryImage", DbType="NVarChar(200)")]
		public string GallaryImage
		{
			get
			{
				return this._GallaryImage;
			}
			set
			{
				if ((this._GallaryImage != value))
				{
					this._GallaryImage = value;
				}
			}
		}
	}
	
	public partial class MS_GetRoomBookingTextDetailByIdResult
	{
		
		private long _Id;
		
		private System.Nullable<long> _RoomBookingId;
		
		private System.Nullable<decimal> _TaxPercentage;
		
		private string _TaxDescription;
		
		public MS_GetRoomBookingTextDetailByIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL")]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoomBookingId", DbType="BigInt")]
		public System.Nullable<long> RoomBookingId
		{
			get
			{
				return this._RoomBookingId;
			}
			set
			{
				if ((this._RoomBookingId != value))
				{
					this._RoomBookingId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxPercentage", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> TaxPercentage
		{
			get
			{
				return this._TaxPercentage;
			}
			set
			{
				if ((this._TaxPercentage != value))
				{
					this._TaxPercentage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxDescription", DbType="NVarChar(200)")]
		public string TaxDescription
		{
			get
			{
				return this._TaxDescription;
			}
			set
			{
				if ((this._TaxDescription != value))
				{
					this._TaxDescription = value;
				}
			}
		}
	}
	
	public partial class MS_GetRoomBookingTextDetailByRoomBookingIdResult
	{
		
		private long _Id;
		
		private System.Nullable<long> _RoomBookingId;
		
		private string _RoomBookingName;
		
		private System.Nullable<decimal> _TaxPercentage;
		
		private string _TaxDescription;
		
		public MS_GetRoomBookingTextDetailByRoomBookingIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL")]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoomBookingId", DbType="BigInt")]
		public System.Nullable<long> RoomBookingId
		{
			get
			{
				return this._RoomBookingId;
			}
			set
			{
				if ((this._RoomBookingId != value))
				{
					this._RoomBookingId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoomBookingName", DbType="NVarChar(200)")]
		public string RoomBookingName
		{
			get
			{
				return this._RoomBookingName;
			}
			set
			{
				if ((this._RoomBookingName != value))
				{
					this._RoomBookingName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxPercentage", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> TaxPercentage
		{
			get
			{
				return this._TaxPercentage;
			}
			set
			{
				if ((this._TaxPercentage != value))
				{
					this._TaxPercentage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxDescription", DbType="NVarChar(200)")]
		public string TaxDescription
		{
			get
			{
				return this._TaxDescription;
			}
			set
			{
				if ((this._TaxDescription != value))
				{
					this._TaxDescription = value;
				}
			}
		}
	}
	
	public partial class MS_GetRoomGallaryByRoomBookingIdResult
	{
		
		private long _Id;
		
		private System.Nullable<long> _RoomBookingId;
		
		private string _RoomBookingName;
		
		private string _GallaryImage;
		
		public MS_GetRoomGallaryByRoomBookingIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL")]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoomBookingId", DbType="BigInt")]
		public System.Nullable<long> RoomBookingId
		{
			get
			{
				return this._RoomBookingId;
			}
			set
			{
				if ((this._RoomBookingId != value))
				{
					this._RoomBookingId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoomBookingName", DbType="NVarChar(200)")]
		public string RoomBookingName
		{
			get
			{
				return this._RoomBookingName;
			}
			set
			{
				if ((this._RoomBookingName != value))
				{
					this._RoomBookingName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GallaryImage", DbType="NVarChar(200)")]
		public string GallaryImage
		{
			get
			{
				return this._GallaryImage;
			}
			set
			{
				if ((this._GallaryImage != value))
				{
					this._GallaryImage = value;
				}
			}
		}
	}
	
	public partial class MS_InsertOrUpdateRoomBookingGallaryResult
	{
		
		private long _InsertedId;
		
		public MS_InsertOrUpdateRoomBookingGallaryResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InsertedId", DbType="BigInt NOT NULL")]
		public long InsertedId
		{
			get
			{
				return this._InsertedId;
			}
			set
			{
				if ((this._InsertedId != value))
				{
					this._InsertedId = value;
				}
			}
		}
	}
	
	public partial class MS_InsertOrUpdateRoomBookingTextDetailResult
	{
		
		private long _InsertedId;
		
		public MS_InsertOrUpdateRoomBookingTextDetailResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InsertedId", DbType="BigInt NOT NULL")]
		public long InsertedId
		{
			get
			{
				return this._InsertedId;
			}
			set
			{
				if ((this._InsertedId != value))
				{
					this._InsertedId = value;
				}
			}
		}
	}
	
	public partial class MS_SearchRoomBookingDetailResult
	{
		
		private System.Nullable<long> _RowNum;
		
		private System.Nullable<int> _Total;
		
		private long _Id;
		
		private System.Nullable<long> _RoomBookingId;
		
		private string _RoomBookingName;
		
		private System.Nullable<decimal> _TaxPercentage;
		
		private string _TaxDescription;
		
		public MS_SearchRoomBookingDetailResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RowNum", DbType="BigInt")]
		public System.Nullable<long> RowNum
		{
			get
			{
				return this._RowNum;
			}
			set
			{
				if ((this._RowNum != value))
				{
					this._RowNum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", DbType="Int")]
		public System.Nullable<int> Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this._Total = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL")]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoomBookingId", DbType="BigInt")]
		public System.Nullable<long> RoomBookingId
		{
			get
			{
				return this._RoomBookingId;
			}
			set
			{
				if ((this._RoomBookingId != value))
				{
					this._RoomBookingId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoomBookingName", DbType="NVarChar(200)")]
		public string RoomBookingName
		{
			get
			{
				return this._RoomBookingName;
			}
			set
			{
				if ((this._RoomBookingName != value))
				{
					this._RoomBookingName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxPercentage", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> TaxPercentage
		{
			get
			{
				return this._TaxPercentage;
			}
			set
			{
				if ((this._TaxPercentage != value))
				{
					this._TaxPercentage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxDescription", DbType="NVarChar(200)")]
		public string TaxDescription
		{
			get
			{
				return this._TaxDescription;
			}
			set
			{
				if ((this._TaxDescription != value))
				{
					this._TaxDescription = value;
				}
			}
		}
	}
	
	public partial class MS_SearchRoomBookingGallaryResult
	{
		
		private System.Nullable<long> _RowNum;
		
		private System.Nullable<int> _Total;
		
		private long _Id;
		
		private System.Nullable<long> _RoomBookingId;
		
		private string _RoomBookingName;
		
		private string _GallaryImage;
		
		public MS_SearchRoomBookingGallaryResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RowNum", DbType="BigInt")]
		public System.Nullable<long> RowNum
		{
			get
			{
				return this._RowNum;
			}
			set
			{
				if ((this._RowNum != value))
				{
					this._RowNum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", DbType="Int")]
		public System.Nullable<int> Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this._Total = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL")]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoomBookingId", DbType="BigInt")]
		public System.Nullable<long> RoomBookingId
		{
			get
			{
				return this._RoomBookingId;
			}
			set
			{
				if ((this._RoomBookingId != value))
				{
					this._RoomBookingId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoomBookingName", DbType="NVarChar(200)")]
		public string RoomBookingName
		{
			get
			{
				return this._RoomBookingName;
			}
			set
			{
				if ((this._RoomBookingName != value))
				{
					this._RoomBookingName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GallaryImage", DbType="NVarChar(200)")]
		public string GallaryImage
		{
			get
			{
				return this._GallaryImage;
			}
			set
			{
				if ((this._GallaryImage != value))
				{
					this._GallaryImage = value;
				}
			}
		}
	}
	
	public partial class MS_GetRoomBookingAllResult
	{
		
		private long _Id;
		
		private string _RoomBookingName;
		
		private string _Description;
		
		private System.Nullable<decimal> _Member;
		
		private System.Nullable<decimal> _Guest;
		
		private string _ProfilePic;
		
		private string _Terms;
		
		public MS_GetRoomBookingAllResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL")]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoomBookingName", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string RoomBookingName
		{
			get
			{
				return this._RoomBookingName;
			}
			set
			{
				if ((this._RoomBookingName != value))
				{
					this._RoomBookingName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(MAX)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Member", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Member
		{
			get
			{
				return this._Member;
			}
			set
			{
				if ((this._Member != value))
				{
					this._Member = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Guest", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Guest
		{
			get
			{
				return this._Guest;
			}
			set
			{
				if ((this._Guest != value))
				{
					this._Guest = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProfilePic", DbType="NVarChar(200)")]
		public string ProfilePic
		{
			get
			{
				return this._ProfilePic;
			}
			set
			{
				if ((this._ProfilePic != value))
				{
					this._ProfilePic = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Terms", DbType="NVarChar(400)")]
		public string Terms
		{
			get
			{
				return this._Terms;
			}
			set
			{
				if ((this._Terms != value))
				{
					this._Terms = value;
				}
			}
		}
	}
	
	public partial class MS_GetRoomBookingByIdResult
	{
		
		private long _Id;
		
		private string _RoomBookingName;
		
		private string _Description;
		
		private System.Nullable<decimal> _Member;
		
		private System.Nullable<decimal> _Guest;
		
		private string _ProfilePic;
		
		private string _Terms;
		
		public MS_GetRoomBookingByIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL")]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoomBookingName", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string RoomBookingName
		{
			get
			{
				return this._RoomBookingName;
			}
			set
			{
				if ((this._RoomBookingName != value))
				{
					this._RoomBookingName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(MAX)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Member", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Member
		{
			get
			{
				return this._Member;
			}
			set
			{
				if ((this._Member != value))
				{
					this._Member = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Guest", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Guest
		{
			get
			{
				return this._Guest;
			}
			set
			{
				if ((this._Guest != value))
				{
					this._Guest = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProfilePic", DbType="NVarChar(200)")]
		public string ProfilePic
		{
			get
			{
				return this._ProfilePic;
			}
			set
			{
				if ((this._ProfilePic != value))
				{
					this._ProfilePic = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Terms", DbType="NVarChar(400)")]
		public string Terms
		{
			get
			{
				return this._Terms;
			}
			set
			{
				if ((this._Terms != value))
				{
					this._Terms = value;
				}
			}
		}
	}
	
	public partial class MS_InsertOrUpdateRoomBookingResult
	{
		
		private long _InsertedId;
		
		public MS_InsertOrUpdateRoomBookingResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InsertedId", DbType="BigInt NOT NULL")]
		public long InsertedId
		{
			get
			{
				return this._InsertedId;
			}
			set
			{
				if ((this._InsertedId != value))
				{
					this._InsertedId = value;
				}
			}
		}
	}
	
	public partial class MS_SearchRoomBookingResult
	{
		
		private System.Nullable<long> _RowNum;
		
		private System.Nullable<int> _Total;
		
		private long _Id;
		
		private string _RoomBookingName;
		
		private string _Description;
		
		private System.Nullable<decimal> _Member;
		
		private System.Nullable<decimal> _Guest;
		
		private string _ProfilePic;
		
		private string _Terms;
		
		public MS_SearchRoomBookingResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RowNum", DbType="BigInt")]
		public System.Nullable<long> RowNum
		{
			get
			{
				return this._RowNum;
			}
			set
			{
				if ((this._RowNum != value))
				{
					this._RowNum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", DbType="Int")]
		public System.Nullable<int> Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this._Total = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL")]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoomBookingName", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string RoomBookingName
		{
			get
			{
				return this._RoomBookingName;
			}
			set
			{
				if ((this._RoomBookingName != value))
				{
					this._RoomBookingName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(MAX)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Member", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Member
		{
			get
			{
				return this._Member;
			}
			set
			{
				if ((this._Member != value))
				{
					this._Member = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Guest", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Guest
		{
			get
			{
				return this._Guest;
			}
			set
			{
				if ((this._Guest != value))
				{
					this._Guest = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProfilePic", DbType="NVarChar(200)")]
		public string ProfilePic
		{
			get
			{
				return this._ProfilePic;
			}
			set
			{
				if ((this._ProfilePic != value))
				{
					this._ProfilePic = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Terms", DbType="NVarChar(400)")]
		public string Terms
		{
			get
			{
				return this._Terms;
			}
			set
			{
				if ((this._Terms != value))
				{
					this._Terms = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
