<?xml version="1.0" encoding="utf-8"?><Database Name="IsconPlatinum_DEV" Class="ServiceSupportDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=192.168.1.80\sql2014;Initial Catalog=IsconPlatinum_DEV;Persist Security Info=True;User ID=sebata" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ECubeCMSConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.CRMGetServiceReportById" Method="CRMGetServiceReportById">
    <Parameter Name="Id" Parameter="id" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="CRMGetServiceReportByIdResult">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="CompanyName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreatedOn" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="TypeName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(8000) NOT NULL" CanBeNull="false" />
      <Column Name="MemberName" Type="System.String" DbType="VarChar(101) NOT NULL" CanBeNull="false" />
      <Column Name="MemberCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ResponseBy" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.CRMUpdateServiceSupport" Method="CRMUpdateServiceSupport">
    <Parameter Name="Id" Parameter="id" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="ServiceSupportTypeId" Parameter="serviceSupportTypeId" Type="System.Int32" DbType="Int" />
    <Parameter Name="StatusId" Parameter="statusId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Description" Parameter="description" Type="System.String" DbType="VarChar(8000)" />
    <Parameter Name="Response" Parameter="response" Type="System.String" DbType="VarChar(8000)" />
    <Parameter Name="ResponceBy" Parameter="responceBy" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="UserId" Parameter="userId" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="PageId" Parameter="pageId" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="CRMUpdateServiceSupportResult">
      <Column Name="InsertedId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.MS_GetServiceSupportType" Method="MS_GetServiceSupportType">
    <ElementType Name="MS_GetServiceSupportTypeResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TypeName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.CRMGetStatusAll" Method="CRMGetStatusAll">
    <ElementType Name="CRMGetStatusAllResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StatusDesc" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.CRMGetServiceSupportById" Method="CRMGetServiceSupportById">
    <Parameter Name="Id" Parameter="id" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="CRMGetServiceSupportByIdResult">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="MemberId" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="ServiceSupportTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StatusId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(8000) NOT NULL" CanBeNull="false" />
      <Column Name="Response" Type="System.String" DbType="VarChar(8000) NOT NULL" CanBeNull="false" />
      <Column Name="ResponseBy" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedOn" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="MemberCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MemberName" Type="System.String" DbType="VarChar(101) NOT NULL" CanBeNull="false" />
      <Column Name="StatusDesc" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="TypeName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.CRMSearchServiceSupport" Method="CRMSearchServiceSupport">
    <Parameter Name="Rows" Parameter="rows" Type="System.Int32" DbType="Int" />
    <Parameter Name="Page" Parameter="page" Type="System.Int32" DbType="Int" />
    <Parameter Name="Search" Parameter="search" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="Sort" Parameter="sort" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="CRMSearchServiceSupportResult">
      <Column Name="RowNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="MemberId" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="ServiceSupportTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StatusId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="Response" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="ResponseBy" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="MemberCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Fname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Lname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreatedOn" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="TypeName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="StatusDesc" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Total" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>