name: SonarQube Quality Gate Check

on:
  push:
    branches:
      - "*" 
      
  pull_request:
    branches:
      - "*" 
jobs:
  sonarqube_analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET 5.x
        uses: actions/setup-dotnet@v3
        with:
              dotnet-version: '5.0.x'    

      - name: Setup MSBuild
        uses: msbuild/setup-msbuild@v1
        with:
                msbuild-version: 'latest'      

      - name: SonarQube Scan
        run: |
          echo "starting analyzing.."  

          dotnet tool install --global dotnet-sonarscanner
          
          SonarScanner.MSBuild.exe begin /k:"eCubeMemberCMSWebApp" /d:sonar.host.url="https://sonarqube.kcspl.in" /d:sonar.token="dca7a8f306acdaa720a1feec1a94215cfa08f846"
          
          MsBuild.exe  /t:Rebuild
          
          SonarScanner.MSBuild.exe end /d:sonar.login="dca7a8f306acdaa720a1feec1a94215cfa08f846"
          
      - name: Check SonarQube Quality Gate    
        run: |
          sudo apt-get install jq
          STATUS=$(curl -s "http://sonarqube.kcspl.in:9000/api/qualitygates/project_status?projectKey=eCubeMemberCMSWebApp" -u "dca7a8f306acdaa720a1feec1a94215cfa08f846" | jq -r '.projectStatus.status'    
          echo "Quality gate values : ${QUALITY_GATE_STATUS}"
          
          if [ "${QUALITY_GATE_STATUS}" != "OK" ]; then
            echo "Quality Gate check failed!"
            exit 1
          else
            echo "Quality Gate check passed!"
          fi
