name: SonarQube Quality Gate Check

on:
  push:
    branches:
      - "*"

  pull_request:
    branches:
      - "*"
jobs:
  sonarqube_analysis:
    runs-on: windows-2019

    steps:
      - name: Add msbuild to PATH
        uses: Dana-Prajea/Setup-MSBuild@v1.1
        with:
          vs-prerelease: true
          vs-version: "[19]"
      - name: java install
        uses: actions/setup-java@v3
        with:
          distribution: "temurin" # See 'Supported distributions' for available options
          java-version: "17"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET 6.x
        uses: actions/setup-dotnet@v3
        with:
          # Semantic version range syntax or exact version of a dotnet version
          dotnet-version: "6.0.x"

      - name: SonarQube Scan
          echo "starting analyzing..."
        run: |
          dotnet tool install --global dotnet-sonarscanner
          dotnet sonarscanner begin /k:"eCubeMemberCMSWebApp" /d:sonar.host.url="http://sonarqube.kcspl.in:9000" /d:sonar.login="82937a40b7dbb37782bacb338c7bca84a24196e9"
          MSBuild.exe /t:Rebuild /p:TargetFramework=net46
          dotnet sonarscanner end /d:sonar.login="82937a40b7dbb37782bacb338c7bca84a24196e9"

      - name: Check SonarQube Quality Gate
        run: |
          echo "Starting quality gate"

          $response = Invoke-WebRequest -Uri "http://sonarqube.kcspl.in:9000/api/qualitygates/project_status?projectKey=eCubeMemberCMSWebApp" -Headers @{ Authorization = "Basic 82937a40b7dbb37782bacb338c7bca84a24196e9" }
          $status = ($response.Content | ConvertFrom-Json).projectStatus.status
          Write-Host "SonarQube Quality Gate status: $status"
          if ($status -ne "OK") {
            Write-Host "Quality Gate check failed!"
            exit 1
          } else {
            Write-Host "Quality Gate check passed!"
          }
