name: SonarQube Quality Gate Check

on:
  push:
    branches:
      - "*" 
      
  pull_request:
    branches:
      - "*" 
jobs:
  sonarqube_analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET 5.x
        uses: actions/setup-dotnet@v3
        with:
              dotnet-version: '5.0.x'       

      - name: SonarQube Scan
        run: |
          echo "starting analyzing.."  

          #dotnet tool install --global dotnet-sonarscanner
          
          pwd
          #curl -v -O https://github.com/SonarSource/sonar-scanner-msbuild/releases/download/5.15.0.80890/sonar-scanner-msbuild-5.15.0.80890-net46.zip
          ls -ltrha
          #find . -name "*.zip" | while read filename; do unzip -o -d "`dirname "$filename"`" "$filename"; done;
          #find . -name "*.zip" | xargs -P 5 -I fileName sh -c 'unzip -o -d "$(dirname "fileName")/$(basename -s .zip "fileName")" "fileName"'
          unzip sonar-scanner-msbuild-5.15.0.80890-net5.0.zip
          ls -ltrha
          export PATH=$PATH:pwd
          
          SonarScanner.MSBuild.exe begin /k:"eCubeMemberCMSWebApp" /d:sonar.host.url="https://sonarqube.kcspl.in" /d:sonar.login="dca7a8f306acdaa720a1feec1a94215cfa08f846"
          MsBuild.exe /t:Rebuild
          SonarScanner.MSBuild.exe end /d:sonar.login="dca7a8f306acdaa720a1feec1a94215cfa08f846"
          
      - name: Check SonarQube Quality Gate    
        run: |
          sudo apt-get install jq
          STATUS=$(curl -s "http://sonarqube.kcspl.in:9000/api/qualitygates/project_status?projectKey=eCubeMemberCMSWebApp" -u "dca7a8f306acdaa720a1feec1a94215cfa08f846" | jq -r '.projectStatus.status'    
          echo "Quality gate values : ${QUALITY_GATE_STATUS}"
          
          if [ "${QUALITY_GATE_STATUS}" != "OK" ]; then
            echo "Quality Gate check failed!"
            exit 1
          else
            echo "Quality Gate check passed!"
          fi
